// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/alles-was-sie-ueber-federraten-wissen-muessen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const allesWasSieUeberFederratenWissenMuessenDE: PageEntry = {
  id: "post.alles-was-sie-ueber-federraten-wissen-muessen",
  locale: "de",
  slug: "alles-was-sie-ueber-federraten-wissen-muessen",
  seo: {
    title: "Alles, was Sie über Federraten wissen müssen | Dietz GmbH",
    description: "Herzlich willkommen zu unserem heutigen Blogbeitrag rund um das Thema Federraten. In diesem Artikel erfahren Sie alles, was Sie über Federraten wissen müssen, um das Beste aus Ihre",
  },
  type: "post",
  h1: "Alles, was Sie über Federraten wissen müssen",
  intro: "Herzlich willkommen zu unserem heutigen Blogbeitrag rund um das Thema Federraten. In diesem Artikel erfahren Sie alles, was Sie über Federraten wissen müssen, um das Beste aus Ihrer Fahrzeugfederung herauszuholen.",
  blocks: [
    { kind: "heading", level: 2, text: "Was sind Federraten?" },
    { kind: "paragraph", text: "Federraten sind ein wichtiger Parameter, der die Steifigkeit einer Fahrzeugfeder angibt. Sie geben an, wie stark eine Feder komprimiert wird, wenn eine bestimmte Kraft auf sie ausgeübt wird. Federraten werden in Newton pro Millimeter (N/mm) gemessen und haben einen großen Einfluss auf das Fahrverhalten eines Fahrzeugs." },
    { kind: "heading", level: 2, text: "Warum sind Federraten wichtig?" },
    { kind: "paragraph", text: "Die richtige Wahl der Federraten kann das Fahrverhalten und den Komfort eines Fahrzeugs erheblich verbessern. Wenn die Federraten zu weich sind, kann dies zu einer zu starken Einfederung und einem schwammigen Fahrverhalten führen. Sind die Federraten hingegen zu hart, kann dies zu einer unkomfortablen Fahrt und einer schlechten Straßenlage führen. Daher ist es wichtig, die passenden Federraten für Ihr Fahrzeug und Ihren Fahrstil zu wählen." },
    { kind: "heading", level: 2, text: "Wie werden Federraten bestimmt?" },
    { kind: "paragraph", text: "Die richtige Bestimmung der Federraten ist entscheidend, um die gewünschte Fahrzeugdynamik zu erreichen. Es gibt verschiedene Faktoren, die bei der Bestimmung der Federraten berücksichtigt werden müssen. Dazu gehören das Fahrzeuggewicht, der Einsatzzweck des Fahrzeugs sowie persönliche Vorlieben in Bezug auf Fahrkomfort und Sportlichkeit. In der Regel wird eine Kombination aus Berechnungen, Erfahrungswerten und Testfahrten verwendet, um die optimalen Federraten festzulegen." },
    { kind: "heading", level: 2, text: "Die Auswirkungen von Federraten auf das Fahrverhalten" },
    { kind: "paragraph", text: "Die Federraten haben direkte Auswirkungen auf das Fahrverhalten eines Fahrzeugs. Eine weichere Federung sorgt für einen größeren Federweg, was zu einer insgesamt komfortableren Fahrt führen kann. Allerdings kann eine zu weiche Federung auch zu einer stärkeren Körperneigung in Kurven und einem schlechteren Handling führen. Eine härtere Federung hingegen ermöglicht eine bessere Straßenlage und eine präzisere Lenkung, kann jedoch zu einer unbequemen Fahrt auf unebenen Straßen führen. Es ist daher wichtig, das richtige Gleichgewicht zu finden und die Federraten entsprechend anzupassen." },
    { kind: "paragraph", text: "Insgesamt spielen Federraten eine entscheidende Rolle für das Fahrverhalten eines Fahrzeugs. Die richtige Wahl der Federraten kann das Fahrverhalten verbessern und den Fahrkomfort erhöhen. Wenn Sie weitere Fragen zu Federraten haben oder Unterstützung bei der Auswahl der passenden Federn für Ihr Fahrzeug benötigen, stehen Ihnen unsere Experten gerne zur Verfügung." }
  ],
};
