// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/alles-was-sie-ueber-die-federpruefung-wissen-muessen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const allesWasSieUeberDieFederpruefungWissenMuessenDE: PageEntry = {
  id: "post.alles-was-sie-ueber-die-federpruefung-wissen-muessen",
  locale: "de",
  slug: "alles-was-sie-ueber-die-federpruefung-wissen-muessen",
  seo: {
    title: "Alles, was Sie über die Federprüfung wissen müssen | Dietz GmbH",
    description: "Die Federprüfung ist ein wichtiger Aspekt bei der Entwicklung und Herstellung von Federn. In diesem Artikel erfahren Sie alles, was Sie darüber wissen müssen.",
  },
  type: "post",
  h1: "Alles, was Sie über die Federprüfung wissen müssen",
  intro: "Die Federprüfung ist ein wichtiger Aspekt bei der Entwicklung und Herstellung von Federn. In diesem Artikel erfahren Sie alles, was Sie darüber wissen müssen.",
  blocks: [
    { kind: "heading", level: 2, text: "Was ist die Federprüfung?" },
    { kind: "paragraph", text: "Die Federprüfung ist ein Prozess, bei dem Federn auf ihre Leistungsfähigkeit und Zuverlässigkeit getestet werden. Sie wird durchgeführt, um sicherzustellen, dass Federn den Anforderungen und Standards entsprechen und ihre Funktion optimal erfüllen." },
    { kind: "heading", level: 3, text: "Warum ist die Federprüfung wichtig?" },
    { kind: "paragraph", text: "Die Federprüfung ist wichtig, um sicherzustellen, dass Federn den hohen Belastungen standhalten, denen sie in verschiedenen Anwendungen ausgesetzt sind. Durch die Prüfung werden mögliche Mängel oder Schwachstellen frühzeitig erkannt, um eine mögliche Produktfehlfunktion zu vermeiden." },
    { kind: "heading", level: 3, text: "Welche Arten der Federprüfung gibt es?" },
    { kind: "paragraph", text: "Es gibt verschiedene Arten der Federprüfung, darunter:" },
    { kind: "list", ordered: true, items: ["Statische Prüfung: Bei dieser Art der Prüfung wird die Feder unter einer konstanten Belastung gehalten, um ihre Deformation und Rückstellkraft zu messen.", "Dynamische Prüfung: Hierbei wird die Feder einer zyklischen Belastung ausgesetzt, um ihre Fähigkeit zur Wiederherstellung der ursprünglichen Form und Funktion zu überprüfen.", "Zug- und Druckprüfung: Diese Prüfungsmethode dient dazu, die Zug- und Druckfestigkeit der Feder zu bestimmen."] },
    { kind: "heading", level: 3, text: "Wie wird die Federprüfung durchgeführt?" },
    { kind: "paragraph", text: "Die Federprüfung erfolgt in der Regel mit Hilfe spezieller Testmaschinen und -geräte. Diese können verschiedene Messungen wie Federkraft, Federkonstante, Federsteifigkeit und Federlebensdauer durchführen." },
    { kind: "paragraph", text: "Zusätzlich zur Prüfung können auch zerstörungsfreie Prüfverfahren wie Röntgen- und Ultraschallprüfungen eingesetzt werden, um mögliche interne Defekte oder Risse zu identifizieren." },
    { kind: "paragraph", text: "Die Ergebnisse der Federprüfung werden in Form von Protokollen und Berichten dokumentiert, um die Einhaltung der Qualitätsstandards nachweisen zu können." },
    { kind: "paragraph", text: "Indem man sich mit der Federprüfung vertraut macht, kann man sicherstellen, dass die verwendeten Federn den Anforderungen gerecht werden und eine zuverlässige Leistung in verschiedenen Anwendungen gewährleisten." }
  ],
};
