// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/ausbildung-zum-fachlagerist-m-w-d/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const ausbildungZumFachlageristMWDDE: PageEntry = {
  id: "post.ausbildung-zum-fachlagerist-m-w-d",
  locale: "de",
  slug: "ausbildung-zum-fachlagerist-m-w-d",
  seo: {
    title: "Ausbildung zum Fachlagerist (m/w/d) | Dietz GmbH",
    description: "Ausbildung zum Fachlagerist (m/w/d)",
  },
  type: "post",
  h1: "Ausbildung zum Fachlagerist (m/w/d)",
  blocks: [
    { kind: "heading", level: 2, text: "Ausbildung zum Fachlagerist (m/w/d)" },
    { kind: "paragraph", text: "Wir sind ein solides, inhabergeführtes Unternehmen der metallverarbeitenden Industrie. An unserem Standort in Oberfranken entwickeln und fertigen wir vorwiegend für die Bereiche Automotive, Medizintechnik und Elektrotechnik kundenspezifische, innovative Federn-, Stanz-, Biegeteile, Baugruppen und auch hybride Baugruppen. Höchste Anforderungen an Werkstoffe, Präzision, Qualität und Liefertreue werden von unseren Mitarbeitern kreativ und zuverlässig für unsere Kunden realisiert." },
    { kind: "heading", level: 2, text: "Unsere Benefits" },
    { kind: "heading", level: 3, text: "Weiterbildung/ Coaching" },
    { kind: "paragraph", text: "Durch regelmäßige Weiterbildungen und Coachings möchten wir gewährleisten, dass unsere Mitarbeiter:innen immer auf dem neuesten Stand sind." },
    { kind: "heading", level: 3, text: "BAV (Dietz Zukunfsplan)" },
    { kind: "paragraph", text: "Mit dem Dietz Zukunftsplan bist du bestens zusätzlich für die Zukunft (Rente) abgesichert." },
    { kind: "heading", level: 3, text: "Mitarbeiter Events" },
    { kind: "paragraph", text: "Durch regelmäßiges Team und Mitarbeiter Events stärken wir das gemeinsame Miteinander." },
    { kind: "heading", level: 3, text: "Flache Hierarchien" },
    { kind: "paragraph", text: "Durch unsere flachen Hierarchien pflegen wir kurze und offene Kommunikationswege." },
    { kind: "heading", level: 3, text: "Jobrad" },
    { kind: "paragraph", text: "Die Gesundheit unserer Mitarbeiter:innen liegt uns am Herzen. Mit dem Jobrad bleibst du fit und es ist der perfekte Ausgleich zum Arbeitsalltag." },
    { kind: "heading", level: 3, text: "Flexible Arbeitszeiten" },
    { kind: "paragraph", text: "Unsere flexiblen Arbeitszeiten ermöglichen es dir Familie und Arbeit bestens zu kombinieren." },
    { kind: "heading", level: 3, text: "Unbefristete Arbeitsverträge" },
    { kind: "paragraph", text: "Genieße langfristige Sicherheit und Stabilität in deiner beruflichen Laufbahn und entfalte deine Ziele und Potenziale voll aus." },
    { kind: "heading", level: 3, text: "Obstkorb" },
    { kind: "paragraph", text: "Um dir eine tägliche Freude zu bereiten und eine ausgewogene Ernährung zu fördern, versorgen wir dich täglich mit frischem Obst." },
    { kind: "heading", level: 3, text: "kostenlose Wasserspender" },
    { kind: "paragraph", text: "Im ganzen Gebäude findest du unsere Wasserspender. Denn uns ist es wichtig, dass unsere Mitarbeiter:innen ihren Wasserbedarf ausreichend decken." },
    { kind: "heading", level: 2, text: "Ausbildungsfakten" },
    { kind: "paragraph", text: "Die Ausbildung zur Fachlageristin/ zum Fachlageristen bei der Dietz GmbH bietet dir die einzigartige Möglichkeit, in die faszinierende Welt der Logistik einzutauchen. Bei uns wirst du ein wichtiger Teil des Teams und trägst dazu bei, unsere logistischen Abläufe noch effizienter zu gestalten. Die Ausbildung zum Fachlageristen dauert zwei Jahre und besteht aus einer betrieblichen Ausbildung im Unternehmen sowie einer schulischen Ausbildung in der Berufsschule in Lichtenfels. Am Ende der zweijährigen Ausbildung legen die angehenden Fachlageristen eine Abschlussprüfung ab. Diese Prüfung besteht aus einem schriftlichen und einem praktischen Teil." },
    { kind: "heading", level: 2, text: "Wir bieten Ihnen" },
    { kind: "list", items: ["Eine fundierte und praxisorientierte Ausbildung in einem erfolgreichen Unternehmen.", "Ein engagiertes und kollegiales Team, das dich unterstützt.", "Die Möglichkeit, deine Stärken und Interessen zu entdecken und weiterzuentwickeln.", "Attraktive Weiterbildungsmöglichkeiten und Perspektiven für deine berufliche Zukunft."] },
    { kind: "heading", level: 2, text: "Ausbildungsinhalte" },
    { kind: "list", items: ["Warenannahme und -kontrolle", "Kommissionierung", "Lagerverwaltung", "Bestandsmanagement", "Qualitätskontrolle", "Versand und Transport", "Arbeitssicherheit und Umweltschutz"] },
    { kind: "heading", level: 2, text: "Ihr Profil" },
    { kind: "list", items: ["Du hast einen guten Schulabschluss (mindestens Hauptschulabschluss).", "Du kannst dich an neue Situationen gut anpassen und bist flexibel.", "Du bist teamfähig und kommunizierst gerne.", "Du hast generell Interesse an logistischen Prozessen und Lagerwirtschaft und möchtest neue Dinge lernen."] },
    { kind: "paragraph", text: "Ihre Ansprechpartnerin" },
    { kind: "paragraph", text: "Andrea Dietz Leitung Personalwesen" },
    { kind: "list", items: ["09568 9442 119", "karriere@dietz.eu"] },
    { kind: "paragraph", text: "Tun Sie Gutes für die Umwelt und füllen Sie direkt hier Ihre grüne, papierlose Bewerbung aus." },
    { kind: "paragraph", text: "Zum Datenschutz" },
    { kind: "image", src: "/images/live/Andrea-Dietz.jpg", alt: "Ausbildung zum Fachlagerist (m/w/d)", width: 773, height: 640 }
  ],
};
