// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/ausbildung2023/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const ausbildung2023DE: PageEntry = {
  id: "post.ausbildung2023",
  locale: "de",
  slug: "ausbildung2023",
  seo: {
    title: "Wir bilden aus 2023 – Ausbildung macht mehr aus uns | Dietz GmbH",
    description: "Wir bilden aus 2023 – Ausbildung macht mehr aus uns",
  },
  type: "post",
  h1: "Wir bilden aus 2023 – Ausbildung macht mehr aus uns",
  blocks: [
    { kind: "heading", level: 2, text: "Wir bilden aus 2023 – Ausbildung macht mehr aus uns" },
    { kind: "paragraph", text: "Die IHK zu Coburg hat die Kampagne #könnenlernen ins Leben gerufen, um junge Menschen für eine Ausbildung zu begeistern. Denn eine Ausbildung bietet nicht nur einen Einstieg in das Berufsleben, sondern auch die Möglichkeit, sich persönlich und beruflich weiterzuentwickeln." },
    { kind: "paragraph", text: "Mit verschiedenen Aktionen und Events möchte die IHK zu Coburg Schülerinnen und Schüler dazu animieren, sich mit verschiedenen Berufsbildern auseinanderzusetzen und herauszufinden, welcher Beruf zu ihren Fähigkeiten und Interessen passt. Denn nur wer seine Stärken kennt, kann auch erfolgreich in seinem Beruf sein." },
    { kind: "paragraph", text: "Die Kampagne #könnenlernen richtet sich dabei nicht nur an Schülerinnen und Schüler, sondern auch an Unternehmen, die Auszubildende suchen – so wie wir. Denn eine Ausbildung bietet Unternehmen die Chance, junge Talente an das Unternehmen zu binden und langfristig zu fördern." },
    { kind: "paragraph", text: "Insgesamt ist die Kampagne #könnenlernen ein wichtiger Schritt, um junge Menschen für eine Ausbildung zu begeistern und ihnen die Chancen aufzuzeigen, die sich durch eine Ausbildung ergeben. Denn nur durch eine fundierte Ausbildung können junge Menschen ihr volles Potential entfalten und erfolgreich ins Berufsleben starten." },
    { kind: "paragraph", text: "Du möchtest mehr über eine Ausbildung bei uns erfahren? Dann informiere dich jetzt und werde künftig ein Teil unseres Teams!" },
    { kind: "image", src: "/images/live/Industriemechaniker-.jpg", alt: "Wir bilden aus 2023 – Ausbildung macht mehr aus uns", width: 1280, height: 674 }
  ],
};
