// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/ausbildung-zum-elektroniker-m-w-d/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const ausbildungZumElektronikerMWDDE: PageEntry = {
  id: "post.ausbildung-zum-elektroniker-m-w-d",
  locale: "de",
  slug: "ausbildung-zum-elektroniker-m-w-d",
  seo: {
    title: "Ausbildung zum Elektroniker (m/w/d) | Dietz GmbH",
    description: "Ausbildung zum Elektroniker (m/w/d)",
  },
  type: "post",
  h1: "Ausbildung zum Elektroniker (m/w/d)",
  blocks: [
    { kind: "heading", level: 2, text: "Ausbildung zum Elektroniker (m/w/d)" },
    { kind: "paragraph", text: "Wir sind ein solides, inhabergeführtes Unternehmen der metallverarbeitenden Industrie. An unserem Standort in Oberfranken entwickeln und fertigen wir vorwiegend für die Bereiche Automotive, Medizintechnik und Elektrotechnik kundenspezifische, innovative Federn-, Stanz-, Biegeteile, Baugruppen und auch hybride Baugruppen. Höchste Anforderungen an Werkstoffe, Präzision, Qualität und Liefertreue werden von unseren Mitarbeitern kreativ und zuverlässig für unsere Kunden realisiert." },
    { kind: "heading", level: 2, text: "Unsere Benefits" },
    { kind: "heading", level: 3, text: "Weiterbildung/ Coaching" },
    { kind: "paragraph", text: "Durch regelmäßige Weiterbildungen und Coachings möchten wir gewährleisten, dass unsere Mitarbeiter:innen immer auf dem neuesten Stand sind." },
    { kind: "heading", level: 3, text: "BAV (Dietz Zukunfsplan)" },
    { kind: "paragraph", text: "Mit dem Dietz Zukunftsplan bist du bestens zusätzlich für die Zukunft (Rente) abgesichert." },
    { kind: "heading", level: 3, text: "Mitarbeiter Events" },
    { kind: "paragraph", text: "Durch regelmäßiges Team und Mitarbeiter Events stärken wir das gemeinsame Miteinander." },
    { kind: "heading", level: 3, text: "Flache Hierarchien" },
    { kind: "paragraph", text: "Durch unsere flachen Hierarchien pflegen wir kurze und offene Kommunikationswege." },
    { kind: "heading", level: 3, text: "Jobrad" },
    { kind: "paragraph", text: "Die Gesundheit unserer Mitarbeiter:innen liegt uns am Herzen. Mit dem Jobrad bleibst du fit und es ist der perfekte Ausgleich zum Arbeitsalltag." },
    { kind: "heading", level: 3, text: "Flexible Arbeitszeiten" },
    { kind: "paragraph", text: "Unsere flexiblen Arbeitszeiten ermöglichen es dir Familie und Arbeit bestens zu kombinieren." },
    { kind: "heading", level: 3, text: "Unbefristete Arbeitsverträge" },
    { kind: "paragraph", text: "Genieße langfristige Sicherheit und Stabilität in deiner beruflichen Laufbahn und entfalte deine Ziele und Potenziale voll aus." },
    { kind: "heading", level: 3, text: "Obstkorb" },
    { kind: "paragraph", text: "Um dir eine tägliche Freude zu bereiten und eine ausgewogene Ernährung zu fördern, versorgen wir dich täglich mit frischem Obst." },
    { kind: "heading", level: 3, text: "kostenlose Wasserspender" },
    { kind: "paragraph", text: "Im ganzen Gebäude findest du unsere Wasserspender. Denn uns ist es wichtig, dass unsere Mitarbeiter:innen ihren Wasserbedarf ausreichend decken." },
    { kind: "heading", level: 2, text: "Ausbildungsfakten" },
    { kind: "paragraph", text: "Deine Ausbildung bei uns: Die Ausbildung zum Elektroniker bei dietz ist der Startpunkt für eine spannende berufliche Reise in der Welt der Elektronik. Wir bieten eine fundierte, praxisnahe Ausbildung, die dir die Möglichkeit gibt, deine Fähigkeiten zu entwickeln und echte Projekte zu betreuen." },
    { kind: "paragraph", text: "Ausbildungsdauer : 3,5 Jahre" },
    { kind: "paragraph", text: "Ausbildungsverlauf: Die Ausbildung erfolgt im dualen System, das heißt, die Auszubildenden wechseln zwischen dem Unternehmen und der Berufsschule (Berufsschule Coburg 1). Die theoretische und praktische Ausbildung wird miteinander verknüpft, um die erworbenen Kenntnisse direkt anwenden zu können." },
    { kind: "heading", level: 2, text: "Wir bieten Ihnen" },
    { kind: "list", items: ["Eine praxisorientierte Ausbildung in einem modernen und innovativen Unternehmen.", "Ein engagiertes Team, das deine berufliche Entwicklung unterstützt und fördert.", "Die Möglichkeit, an spannenden Projekten zu arbeiten und eigenverantwortlich Aufgaben zu übernehmen.", "Perspektiven für eine langfristige Karriere in einem wachsenden Unternehmen."] },
    { kind: "heading", level: 2, text: "Ausbildungsinhalte" },
    { kind: "list", items: ["Installation und Instandhaltung", "Entwicklung elektronischer Schaltungen und Systeme", "Fehlersuche und -behebung", "Überprüfung bestehender Anlagen/Systeme", "Arbeitssicherheit und Umweltschutz"] },
    { kind: "heading", level: 2, text: "Ihr Profil" },
    { kind: "list", items: ["Du hast einen guten Schulabschluss (mindestens Hauptschulabschluss).", "Du zeigst Interesse an Elektronik und Technik.", "Du bist handwerklich geschickt und kannst präzise arbeiten.", "Du bist teamfähig, zuverlässig und zeigst Eigeninitiative."] },
    { kind: "paragraph", text: "Ihre Ansprechpartnerin" },
    { kind: "paragraph", text: "Andrea Dietz Leitung Personalwesen" },
    { kind: "list", items: ["09568 9442 119", "karriere@dietz.eu"] },
    { kind: "paragraph", text: "Tun Sie Gutes für die Umwelt und füllen Sie direkt hier Ihre grüne, papierlose Bewerbung aus." },
    { kind: "paragraph", text: "Zum Datenschutz" },
    { kind: "image", src: "/images/live/Andrea-Dietz.jpg", alt: "Ausbildung zum Elektroniker (m/w/d)", width: 773, height: 640 }
  ],
};
