// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/baufortschritt-in-sonneberg/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const baufortschrittInSonnebergDE: PageEntry = {
  id: "post.baufortschritt-in-sonneberg",
  locale: "de",
  slug: "baufortschritt-in-sonneberg",
  seo: {
    title: "Baufortschritt in Sonneberg | Dietz GmbH",
    description: "Baufortschritt in Sonneberg",
  },
  type: "post",
  h1: "Baufortschritt in Sonneberg",
  blocks: [
    { kind: "heading", level: 2, text: "Baufortschritt in Sonneberg" },
    { kind: "heading", level: 3, text: "Firmenentwicklung" },
    { kind: "paragraph", text: "Auf unserer Baustelle am Standort Sonneberg geht es kräftig voran. Pünktlich zum Start in den Herbst ist der Stahlbau der neuen Produktions- und Lagerhalle, die ab Dezember bezugsfertig sein wird, fertig geworden. In der neuen Halle werden die Montagetechnik und ein Teil der Logistik Platz finden. Die Technikräume, in denen der künftige Maschinenpark ausreichend Platz findet, werden aktuell gebaut. Für die zweite Oktoberwoche ist dann das Setzen der Bodenplatte anberaumt – so nimmt unser neuer Standort Schritt für Schritt und ganz nach Plan Gestalt an." },
    { kind: "paragraph", text: "Zu den aktuellen Arbeiten gehört neben dem reinen Bau aber auch das Hallenlayout. Dieses ist für optimale Wege innerhalb der Halle entscheidend und trägt maßgeblich dazu bei, die Arbeitsabläufe effi zient zu gestalten. Zu diesem Zweck erarbeiten Experten des Fraunhofer Instituts aktuell die Hallenplanung und entwickeln dafür die optimale Positionierung unserer Maschinen." },
    { kind: "paragraph", text: "Damit sich alle Mitarbeiterinnen und Mitarbeiter dann ein Bild der neuen Produktions- und Lagerhalle machen können, laden wir die gesamte Belegschaft zu unserer internen Weihnachtsfeier am letzten Arbeitstag in diesem Jahr, dem 22. Dezember, herzlich nach Sonneberg ein. Bis dahin werden wir den Umzug abgeschlossen haben, damit unsere Abteilung Montagetechnik gleich zu Jahresbeginn 2017 frisch ans Werk gehen kann." }
  ],
};
