// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/branchen/weisse-ware/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const branchenWeisseWareDE: PageEntry = {
  id: "post.branchen-weisse-ware",
  locale: "de",
  slug: "branchen/weisse-ware",
  seo: {
    navLabel: "Weiße Ware",
    title: "Federn für Weiße Ware und Hausgeräte | Dietz GmbH",
    description:
      "Federn und Biegeteile für Weiße Ware: Schenkelfedern für Geschirrspüler, Waschmaschinen und Hausgeräte in Serie. Jetzt Anfrage stellen.",
  },
  type: "post",
  h1: "Weiße Ware bei Dietz Federn",
  summary:
    "Komponenten und Baugruppen für Kühlschränke, Geschirrspüler, Waschmaschinen, Trockner und Herde.",
  keyTakeaways: [
    "Komponenten für Kühlschränke, Geschirrspüler, Waschmaschinen, Trockner und Herde.",
    "Vertrauenswürdiger Partner für Kunden in Deutschland und international.",
    "Kontinuierliche Prozessoptimierung und Umsetzung neuer Technologien.",
  ],
  blocks: [
    { kind: "heading", level: 2, text: "Weiße Ware" },
    { kind: "paragraph", text: "Die Dietz GmbH ist ein führendes Unternehmen in der Branche der Weißen Ware. Unsere langjährige Erfahrung und unser Know-how haben uns zu einem vertrauenswürdigen Partner für Kunden in Deutschland und international gemacht." },
    { kind: "paragraph", text: "In der Branche der Weißen Ware sind wir darauf spezialisiert, hochwertige komponenten und Baugruppen für Haushaltsgeräte herzustellen. Dazu gehören unter anderem Komponenten für Kühlschränke, Geschirrspüler, Waschmaschinen, Trockner und Herde. Unsere Produkte zeichnen sich durch ihre hohe Qualität, Funktionalität und Effizienz aus." },
    { kind: "heading", level: 3, text: "Weiße Ware – mit Baugruppen von Dietz" },
    { kind: "paragraph", text: "Als innovatives Unternehmen investieren wir kontinuierlich an der Optimierung unserer Prozesse und der Umsetzung neuer Technologien, um unseren Kunden stets die neuesten Technologien und fortschrittlichen Features bieten zu können. Wir verstehen die Bedürfnisse unserer Kunden und sind bestrebt, Lösungen anzubieten, die ihr Leben erleichtern und optimieren." },
    { kind: "paragraph", text: "Bei der Produktion legen wir größten Wert auf Nachhaltigkeit und Umweltverträglichkeit. Unsere Produkte werden an Energieeffizienten Maschinen hergestellt und tragen somit zur Reduzierung des Energieverbrauchs und der CO²-Emissionen bei. Dies ist uns ein wichtiges Anliegen, da wir unsere Verantwortung gegenüber der Umwelt ernst nehmen." },
    { kind: "paragraph", text: "Unsere kundenindividuelle Produkte bieten für jeden das passende Produkt. Egal, ob es um die Kühlung von Lebensmitteln, das Spülen von Geschirr, die Reinigung von Kleidung oder das Zubereiten von Speisen geht – wir haben die richtige Lösung." },
    { kind: "paragraph", text: "Wir sind stolz darauf, dass unsere Produkte durch ihre hohe Qualität und Langlebigkeit überzeugen." },
    { kind: "paragraph", text: "Als internationales Unternehmen beliefern wir Kunden auf der ganzen Welt, denn wir arbeiten eng mit Namhaften Hertsellern zusammen. Die Dietz GmbH ist stolz darauf, ein verlässlicher Partner in der Branche der Weißen Ware zu sein. Wir setzen hohe Standards in Bezug auf Qualität, Nachhaltigkeit und Kundenzufriedenheit. Mit unseren innovativen Produkten und unseren modernen Herstellungsverfahren streben wir danach, die weiterverarbeitung unserer Produkte angenehmer und komfortabler zu gestalten." },
  ],
  gallery: [
    { heading: "Spulenkörper", caption: "Hybridteil zur weiteren Verarbeitung zur Aufnahme verschiedener Kupferspulen. Vollautomatischer Montageprozess in einem Bihler Stanzautomat. Montage von einem Blech mit integrierter Verschraubung mit anschließendem Fügen in das Kunststoffteil", href: "/produkte/spulenkoerper/", image: { src: "/images/live/DTZ-spulenkoerper.jpg", alt: "Spulenkörper" } },
    { heading: "Sonderdruckfeder mit lötbarer Oberfläche", caption: "Weiterverarbeitung in einer SMT-Bestückung und Einsatz der Platinen in unterschiedlichsten Haushaltsgeräten mit Touchfeldern. Neben der hohen Genauigkeitsanforderung muss die automatische Zuführbarkeit sichergestellt werden", href: "/produkte/sonderdruckfeder-mit-loetbarer-oberflaeche/", image: { src: "/images/live/DTZ_sonderdruckfeder.jpg", alt: "Sonderdruckfeder mit lötbarer Oberfläche" } },
    { heading: "Schenkelfedern zum Öffnen einer Klappe bei Geschirrspülmaschinen", caption: "Sonderwerkzeuge für spezielle Biegeabläufe", href: "/produkte/schenkelfedern-zum-oeffnen-einer-klappe-bei-geschirrspuelmaschinen/", image: { src: "/images/live/dtz-schenkelfeder-geschirrsp.jpg", alt: "Schenkelfedern zum Öffnen einer Klappe bei Geschirrspülmaschinen" } },
    { heading: "Montageteil Maschinenbau", caption: "Platinen schneiden, biegen im Musterbau, vernieten der einzelnen Elemente. Zur Funktion ist zu sagen, dass zwischen den Federblechen ein zylindrischer Körper mit Durchmesser Ø38,7 +/-0,2 mm fixiert und damit in Position gehalten werden soll", href: "/produkte/montageteil-maschinenbau/", image: { src: "/images/live/dtz-montageteil-maschinenbau.jpg", alt: "Montageteil Maschinenbau" } },
  ],
};
