// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/dietz-sagt-hallo-bei-linkedin-und-xing-2/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const dietzSagtHalloBeiLinkedinUndXing2DE: PageEntry = {
  id: "post.dietz-sagt-hallo-bei-linkedin-und-xing-2",
  locale: "de",
  slug: "dietz-sagt-hallo-bei-linkedin-und-xing-2",
  seo: {
    title: "Ein Blick in das neue Verwaltungsgebäude | Dietz GmbH",
    description: "Ein Blick in das neue Verwaltungsgebäude",
  },
  type: "post",
  h1: "Ein Blick in das neue Verwaltungsgebäude",
  blocks: [
    { kind: "heading", level: 2, text: "Ein Blick in das neue Verwaltungsgebäude" },
    { kind: "paragraph", text: "Wir präsentieren: Unser neues Verwaltungsgebäude an unserem Hauptsitz in Neustadt bei Coburg." },
    { kind: "paragraph", text: "Der Spatenstich für dieses Gebäude erfolgte bereits am 10. Mai 2019. Nach einer einjährigen Bauphase konnten dann, im April 2020, diverse Abteilungen wie Qualitäts- und Umweltmanagement, IT, Einkauf, Finanzbuchhaltung, Controlling, Geschäftsführung, Personalabteilung, Vertrieb und das Innovations- und Prozessmanagement ihre neuen Räumlichkeiten beziehen. Zudem bietet das Gebäude neue Besprechungsräume, aber auch Kaffee- und Küchenecken auf jeder Etage." },
    { kind: "paragraph", text: "Absolute Highlights sind vor allem die Terrassenfläche vor dem Verwaltungsgebäude und die Dachterrasse, welche bei gutem Wetter sehr gerne von unseren Mitarbeitern, mit Blick aufs Grüne, genutzt werden. Apropos, auch unsere Dachfläche wurde inzwischen begrünt. Dies ist nicht nur schön anzusehen, sie bietet auch viele Vorteile: eine verbesserte Wärmedämmung im Winter, Hitzeschild im Sommer, erhöhter Schallschutz und zusätzlicher Lebensraum für Tiere." },
    { kind: "paragraph", text: "Wir sind besonders stolz darauf, dass unser neues Gebäude energieautark ist und über 85 % seines Energiebedarfs selbstständig erzeugt. Ebenso konnten viele technische Details umgesetzt werden – Gebäudeautomation, Batteriespeicher, Lüftungsanlage und eine Photovoltaikanlage." },
    { kind: "paragraph", text: "Nicht nur unsere Besucher sind immer wieder beeindruckt, wenn sie das neue Verwaltungsgebäude betreten – auch wir freuen uns täglich aufs Neue." }
  ],
};
