// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/en/enterprise/sustainability/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const enterpriseSustainabilityEN: PageEntry = {
  id: "post.unternehmen-qualitaet-umwelt",
  locale: "en",
  slug: "enterprise/sustainability",
  seo: {
    navLabel: "Sustainability",
    title: "Sustainability at Dietz Federn",
    description: "Sustainability at Dietz Federn",
  },
  type: "post",
  h1: "Sustainability at Dietz Federn",
  blocks: [
    { kind: "image", src: "/images/live/iStock-1224559504-scaled-e1702991179392-1200x376.jpg", alt: "Sustainability at Dietz Federn", width: 512, height: 160 },
    { kind: "heading", level: 2, text: "Sustainability & Environmental Protection" },
    { kind: "heading", level: 2, text: "Our goal is a future fit for our grandchildren" },
    { kind: "paragraph", text: "The basic idea of sustainability is anchored in the family philosophy. Our company’s strategy is to hand over operations to the next generation without major environmental impacts." },
    { kind: "image", src: "/images/live/dietz-ua-icons-blau_vielfalt.png", alt: "Sustainability at Dietz Federn", width: 208, height: 208 },
    { kind: "paragraph", text: "In 2022, we finally incorporated the long-standing sustainability concept into our company’s integrated management system in the form of sustainability management. The construction of the new administration building in 2020 was the beginning of numerous sustainable projects. Of course, the use of a PV system for self-sufficiency and a heat pump was not dispensed with. Sensors were installed for uniform light intensity and office workstations were mainly equipped with height-adjustable desks. This resulted in various energy-saving measures and efficient work processes in the administration, including paperless workflows. In production, for example, a heat recovery system and a cascaded heating system were installed, and lubricants and auxiliary materials were continuously substituted." },
    { kind: "paragraph", text: "Every year, we take on new challenges and work towards our environmental and sustainability goals. The principle is to produce the highest quality through sustainable management. In addition to the environment and energy, our corporate policy also includes quality as well as occupational health and safety." },
    { kind: "heading", level: 2, text: "Our Objectives" },
    { kind: "heading", level: 3, text: "Biodiversity" },
    { kind: "paragraph", text: "The cooperation with the Environment+Climate Pact Bavaria supports several projects on and off the company premises in the region. In addition, the Dietz family forest grows through the plantings of our jubilarians." },
    { kind: "image", src: "/images/live/dietz-ua-icons-blau_energie.png", alt: "Sustainability at Dietz Federn", width: 208, height: 208 },
    { kind: "heading", level: 3, text: "Energy consumption and energy production" },
    { kind: "paragraph", text: "To operate the machinery and our climate-friendly heat pump in the administration building, only green electricity from our PV system and hydropower is used. To heat the premises, compensated natural gas is burned in an efficient cascaded natural gas heating system. In order to increase effectiveness, continuous improvement processes are intertwined." },
    { kind: "image", src: "/images/live/dietz-ua-icons-blau_Wasser.png", alt: "Sustainability at Dietz Federn", width: 208, height: 208 },
    { kind: "heading", level: 3, text: "Dealing with water" },
    { kind: "paragraph", text: "Water is a valuable resource. Careful and responsible use of water in our operations is an integral part of our everyday life." },
    { kind: "image", src: "/images/live/dietz-ua-icons-blau_Abfallmanagement.png", alt: "Sustainability at Dietz Federn", width: 208, height: 208 },
    { kind: "heading", level: 3, text: "Waste management" },
    { kind: "paragraph", text: "The best waste is the one that is not created in the first place. We try to keep the generation of waste as low as possible. Waste generated is separated and recycled or disposed of as far as possible under the management of a disposal matrix and waste balance." },
    { kind: "image", src: "/images/live/dietz-ua-icons-blau_EMobilitaet.png", alt: "Sustainability at Dietz Federn", width: 208, height: 208 },
    { kind: "heading", level: 3, text: "Vehicle fleet" },
    { kind: "paragraph", text: "Our company fleet has been in a state of flux since 2019. In addition to vehicles with conventional and hybrid drives, the trend is towards fully electrically powered vehicles. We can recharge our batteries with electricity via our PV system on our green roof." },
    { kind: "heading", level: 3, text: "Material Efficiency" },
    { kind: "paragraph", text: "Resource consumption must be as low and responsible as possible. Material efficiency is a reflection of our material use and yield. By comparing the input and output of quantities of products, we can identify our shortcomings and Initiate improvement measures." },
    { kind: "heading", level: 3, text: "Greenhouse gas emissions" },
    { kind: "paragraph", text: "Since 2020 (base year), we at DIETZ have been compiling our CO2 footprint or Corporate Carbon Footprint (CCF) in accordance with the guidelines of the Greenhause Gas Protocol (GHG Protocol). We have opted for the “cradle-to-gate” approach, which includes the areas of Scope 1 and 2 as well as Scope 3 of the upstream value chain. We create opportunities for the creation of the product carbon footprint for all products." },
    { kind: "heading", level: 3, text: "Communication" },
    { kind: "paragraph", text: "For Dietz, communication means: – Annual internal environmental week -Intranet – Regular information rounds on the topic of NH – Presentations in networks – Social media – Voluntary sustainability report – Environmental corners in production – Use of external information exhibitions" },
    { kind: "heading", level: 3, text: "Bless you" },
    { kind: "paragraph", text: "For Dietz, promoting health means: – Internal health campaigns – Company-owned gym – Monthly fruit basket – Free drinking water vending machine – Height-adjustable desks – Job Bike Leasing" },
    { kind: "heading", level: 2, text: "Certifications and Memberships" },
    { kind: "heading", level: 2, text: "Partner" },
    { kind: "paragraph", text: "On our way to sustainable development, we work together with various networks and partners to create ecological, economic and social added value for both parties." }
  ],
};
