// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/en/everything-you-need-to-know-about-spring-rates/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const everythingYouNeedToKnowAboutSpringRatesEN: PageEntry = {
  id: "post.alles-was-sie-ueber-federraten-wissen-muessen",
  locale: "en",
  slug: "everything-you-need-to-know-about-spring-rates",
  seo: {
    title: "Everything you need to know about spring rates | Dietz GmbH",
    description: "Welcome to today’s blog post on the subject of spring rates. In this article, you will learn everything you need to know about spring rates to get the best out of your vehicle susp",
  },
  type: "post",
  h1: "Everything you need to know about spring rates",
  intro: "Welcome to today’s blog post on the subject of spring rates. In this article, you will learn everything you need to know about spring rates to get the best out of your vehicle suspension.",
  blocks: [
    { kind: "heading", level: 2, text: "What are spring rates?" },
    { kind: "paragraph", text: "Spring rates are an important parameter that indicates the stiffness of a vehicle spring. They indicate how strongly a spring is compressed when a certain force is applied to it. Spring rates are measured in Newtons per millimeter (N/mm) and have a major influence on the handling of a vehicle." },
    { kind: "heading", level: 2, text: "Why are spring rates important?" },
    { kind: "paragraph", text: "The right choice of spring rates can significantly improve the handling and comfort of a vehicle. If the spring rates are too soft, this can lead to excessive deflection and a spongy ride. However, if the spring rates are too hard, this can lead to an uncomfortable ride and poor road holding. It is therefore important to choose the right spring rates for your vehicle and your driving style." },
    { kind: "heading", level: 2, text: "How are spring rates determined?" },
    { kind: "paragraph", text: "The correct determination of the spring rates is crucial in order to achieve the desired vehicle dynamics. There are various factors that must be taken into account when determining spring rates. This includes the vehicle weight, the intended use of the vehicle and personal preferences in terms of driving comfort and sportiness. As a rule, a combination of calculations, empirical values and test drives is used to determine the optimum spring rates." },
    { kind: "heading", level: 2, text: "The effects of spring rates on driving behavior" },
    { kind: "paragraph", text: "The spring rates have a direct effect on the handling of a vehicle. Softer suspension provides greater suspension travel, which can lead to a more comfortable ride overall. However, suspension that is too soft can also lead to greater body lean when cornering and poorer handling. Harder suspension, on the other hand, enables better road holding and more precise steering, but can lead to an uncomfortable ride on uneven roads. It is therefore important to find the right balance and adjust the spring rates accordingly." },
    { kind: "paragraph", text: "Overall, spring rates play a decisive role in the handling of a vehicle. The right choice of spring rates can improve handling and increase ride comfort. If you have any further questions about spring rates or need assistance in selecting the right springs for your vehicle, our experts will be happy to help." }
  ],
};
