// Originally generated by scripts/migrate/gen-from-live.py from
// https://www.dietz.eu/karriere/, then restructured by hand onto the
// `career-hub` type.
//
// The migration had flattened this page into 59 undifferentiated blocks: the
// seven company values became seven bare paragraphs, the eleven benefits became
// eleven heading/paragraph pairs, the HR contact became a paragraph followed by
// a bullet list containing a phone number, and the vacancies became one `list`
// of run-on strings — so a candidate could read a job title and had no way to
// open it. Every string below is the live site's own copy, only re-homed into
// fields the CareerHub template already knew how to render.
import type { PageEntry } from "@/content/schema";

export const karriereDE: PageEntry = {
  id: "post.karriere",
  locale: "de",
  slug: "karriere",
  seo: {
    navLabel: "Karriere",
    title: "Karriere bei Dietz: Stellen, Ausbildung & Duales Studium",
    description:
      "Offene Stellen, Ausbildungsplätze, duales Studium und Praktika bei der Dietz GmbH in Neustadt bei Coburg. Inhabergeführt, flexible Arbeitszeiten, betriebliche Krankenversicherung.",
  },
  type: "career-hub",
  h1: "Starte deine Karriere bei Dietz Federn!",
  intro:
    "Du suchst einen Job, eine Ausbildung, ein duales Studium oder ein Praktikum? Bei uns erwartet dich ein inhabergeführtes Unternehmen mit flachen Hierarchien – seit über 90 Jahren.",
  blocks: [
    { kind: "image", src: "/images/stills/kollegen-fertigung.jpg", alt: "Zwei Mitarbeiter im Gespräch in der Fertigung", width: 1280, height: 549 },
    { kind: "paragraph", text: "Als führender Hersteller von Präzisionsfedern, Stanz-Umformteilen und hybriden Baugruppen beliefern wir namhafte Kunden z. B. aus der Automobil- und Elektroindustrie oder der Haus- und Medizintechnik. Wir sind Profis unseres Fachs – das seit über 90 Jahren. Unser Name steht nicht umsonst für High-Tech, Präzision und Qualität." },
    { kind: "paragraph", text: "Wir legen großen Wert auf deine persönliche Entwicklung und unterstützen dich aktiv in deiner Karriere. Wir sind mehr als nur ein Arbeitsplatz – die Dietz GmbH ist eine Gemeinschaft, die zusammenhält. Unsere offene Unternehmenskultur ermöglicht es dir, Ideen einzubringen und wirklich etwas zu bewegen!" },
    { kind: "paragraph", text: "Bereit für die Herausforderung? Entdecke unsere Stellenangebote und bewirb dich jetzt! Deine Karriere bei Dietz GmbH beginnt hier." },
    { kind: "paragraph", text: "Firma Dietz unterstützt Auszubildende, die ein Auslandspraktikum über Erasmus machen möchten." },
  ],
  cards: [
    { title: "Fachkräfte", href: "/karriere/fachkraefte/", body: "Du suchst nach einer passenden Arbeitsstelle? Hier bist du richtig.", thumb: "/images/career/Elektroniker.jpg" },
    { title: "Ausbildung", href: "/karriere/ausbildung/", body: "Hier findest du alles über unsere kaufmännischen oder gewerblichen Ausbildungsstellen.", thumb: "/images/career/Industriekauffrau.jpg" },
    { title: "Duales Studium", href: "/karriere/duales-studium/", body: "Setze bei uns fachliches Wissen verknüpft mit tiefgehender Praxisausbildung um.", thumb: "/images/career/Produktdesigner.jpg" },
    { title: "Praktikum", href: "/karriere/praktikum/", body: "Lust, einfach mal bei uns reinzuschnuppern? Lerne die Fertigung und die Büros im Praktikum kennen.", thumb: "/images/career/Auszubildender-Paul.jpg" },
    { title: "Initiativbewerbung", href: "/karriere/initativbewerbung/", body: "Keine passende Stelle dabei? Dann freuen wir uns über deine Initiativbewerbung.", thumb: "/images/career/Lageristin.jpg" },
  ],
  values: [
    "ein familienfreundliches Klima",
    "den Rücken freizuhalten",
    "Zuverlässigkeit",
    "Nachhaltigkeit",
    "Bodenständigkeit",
    "Persönlichkeit",
    "aufrichtige Kommunikation",
  ],
  benefits: [
    { title: "Inhaber geführt", body: "Das Traditionsunternehmen ist auch heute noch Inhaber geführt, so sorgen wir dafür, dass unsere Unternehmenswerte stets vertreten werden." },
    { title: "Weiterbildung / Coaching", body: "Durch regelmäßige Weiterbildungen und Coachings möchten wir gewährleisten, dass unsere Mitarbeitenden immer auf dem neuesten Stand sind." },
    { title: "BAV (Dietz Zukunftsplan)", body: "Mit dem Dietz Zukunftsplan bist du bestens zusätzlich für die Zukunft (Rente) abgesichert." },
    { title: "Mitarbeiter Events", body: "Durch regelmäßiges Team und Mitarbeiter Events stärken wir das gemeinsame Miteinander." },
    { title: "Flache Hierarchien", body: "Durch unsere flachen Hierarchien pflegen wir kurze und offene Kommunikationswege." },
    { title: "Jobrad", body: "Die Gesundheit unserer Mitarbeitenden liegt uns am Herzen. Mit dem Jobrad bleibst du fit und es ist der perfekte Ausgleich zum Arbeitsalltag." },
    { title: "Flexible Arbeitszeiten", body: "Unsere flexiblen Arbeitszeiten ermöglichen es dir Familie und Arbeit bestens zu kombinieren." },
    { title: "Unbefristete Arbeitsverträge", body: "Genieße langfristige Sicherheit und Stabilität in deiner beruflichen Laufbahn und entfalte deine Ziele und Potenziale voll aus." },
    { title: "monatlicher Obstkorb", body: "Um dir eine Freude zu bereiten und eine ausgewogene Ernährung zu fördern, versorgen wir dich mit verschiedenen Obstsorten." },
    { title: "kostenlose Wasserspender", body: "Im ganzen Gebäude findest du unsere Wasserspender. Denn uns ist es wichtig, dass unsere Mitarbeitenden ihren Wasserbedarf ausreichend decken." },
    { title: "betriebliche Krankenversicherung", body: "Die Gesundheit unserer Mitarbeitenden liegt uns am Herzen. Daher bieten wir allen Mitarbeitenden eine betriebliche Krankenversicherung an." },
  ],
  jobs: [
    { title: "Elektroniker (m/w/d)", href: "/elektroniker-m-w-d/", kind: "Fachkraft", hours: "ab sofort, Vollzeit" },
    { title: "Maschineneinrichter Stanz- und Umformtechnik (m/w/d)", href: "/maschineneinrichter-stanz-umformtechnik-m-w-d/", kind: "Fachkraft", hours: "ab sofort, Vollzeit" },
    { title: "Reinigungskraft (m/w/d) mit Leidenschaft für Ordnung", href: "/reinigungskraft-mwd-mit-leidenschaft-fuer-ordnung/", kind: "Fachkraft", hours: "ab sofort, Teilzeit oder Vollzeit" },
    { title: "Ausbildung zum Industriekaufmann/-frau (m/w/d)", href: "/ausbildung-zum-industriekaufmann-frau-m-w-d/", kind: "Ausbildung", hours: "Vollzeit" },
    { title: "Ausbildung zum Industriemechaniker/Werkzeugmechaniker (m/w/d)", href: "/ausbildung-zum-industriemechaniker-werkzeugmechaniker-m-w-d/", kind: "Ausbildung", hours: "Vollzeit" },
    { title: "Ausbildung zur Fachkraft für Lagerlogistik (m/w/d)", href: "/ausbildung-zur-fachkraft-fuer-lagerlogistik-m-w-d/", kind: "Ausbildung", hours: "Vollzeit" },
    { title: "Ausbildung zum Elektroniker (m/w/d)", href: "/ausbildung-zum-elektroniker-m-w-d/", kind: "Ausbildung", hours: "Vollzeit" },
    { title: "Ausbildung zum Fachlagerist (m/w/d)", href: "/ausbildung-zum-fachlagerist-m-w-d/", kind: "Ausbildung", hours: "Vollzeit" },
    { title: "Ausbildung zum Technischen Produktdesigner (m/w/d)", href: "/ausbildung-zum-technischen-produktdesigner/", kind: "Ausbildung", hours: "Vollzeit" },
    { title: "Ausbildung zum Maschinen-/Anlagenführer (m/w/d)", href: "/ausbildung-zum-zur-maschinen-anlagenfuehrer-in/", kind: "Ausbildung", hours: "Vollzeit" },
  ],
  contact: {
    name: "Andrea Dietz",
    role: "Leitung Personalwesen",
    phone: "09568 9442 119",
    email: "karriere@dietz.eu",
    photo: "/images/career/Andrea-Dietz.jpg",
  },
};
