// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/schenkelfedermaschine-fmu-08/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const schenkelfedermaschineFmu08DE: PageEntry = {
  id: "post.schenkelfedermaschine-fmu-08",
  locale: "de",
  slug: "schenkelfedermaschine-fmu-08",
  seo: {
    title: "Schenkelfedermaschine FMU 08 | Dietz GmbH",
    description: "Schenkelfedermaschine FMU 08",
  },
  type: "post",
  h1: "Schenkelfedermaschine FMU 08",
  blocks: [
    { kind: "heading", level: 2, text: "Schenkelfedermaschine FMU 08" },
    { kind: "heading", level: 3, text: "Firmenentwicklung" },
    { kind: "paragraph", text: "Der jüngste Neuzugang in unserem Maschinenpark ist die Wafios-Schenkelfedermaschine FMU 08, die zur Herstellung von Federn aller Art eingesetzt werden kann. Die neue Schenkelfedermaschine erhöht unsere Produktionsleistung bei optimierten Stückkosten und punktet durch einen besonders hohen Bedienkomfort. Seit 01.09 ist sie in unsere Produktion eingebunden und erweitert unsere Kapazitäten im Bereich Schenkelfedern." },
    { kind: "paragraph", text: "Folgende Vorteile bietet diese Maschine: • Verbesserung des Preis-/Leistungsverhältnisses • Produktion eines breiten Teilespektrums durch modulares Maschinenkonzept • perfekt für kleine und mittelgroße Serien durch höchste Flexibilität und Universalität • Nullfehlerproduktion durch moderne Überwachungsund Regelungstechnik • CE-konforme Sicherheitseinrichtung • hoher Qualitätsstandard führt zu langer Lebensdauer, hoher Maschinenverfügbarkeit und schnellerer Amortisation • komfortable Programmierung komplexer Federgeometrien und CNC-Abläufe durch WAFIOS WPS 3.2 EasyWay mit EasyTab • hohe Energie-Effizienz • iQspring: Simulation, Taktzeitermittlung und Kollisionskontrolle" }
  ],
};
