// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/spiralfedern-anwendungen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const spiralfedernAnwendungenDE: PageEntry = {
  id: "post.spiralfedern-anwendungen",
  locale: "de",
  slug: "spiralfedern-anwendungen",
  seo: {
    title: "Präzision und Leistung: Spiralfedern und ihre Anwendungen | Dietz GmbH",
    description: "Spiralfedern sind vielseitige und unverzichtbare Komponenten in verschiedenen Branchen, von der Uhrenindustrie bis zum Maschinenbau. Diese Rückstellelemente bieten ein linear anste",
  },
  type: "post",
  h1: "Präzision und Leistung: Spiralfedern und ihre Anwendungen",
  intro: "Spiralfedern sind vielseitige und unverzichtbare Komponenten in verschiedenen Branchen, von der Uhrenindustrie bis zum Maschinenbau. Diese Rückstellelemente bieten ein linear ansteigendes Drehmoment und werden in zahlreichen Anwendungen eingesetzt. In diesem Artikel werden wir uns eingehend mit ihnen befassen, ihre Funktionsweise verstehen und die verschiedenen Anwendungen erkunden, in denen sie zum Einsatz kommen.",
  blocks: [
    { kind: "heading", level: 2, text: "Die Grundlagen von Spiralfedern" },
    { kind: "heading", level: 3, text: "Aufbau und Materialien" },
    { kind: "paragraph", text: "Sie bestehen aus einem kontinuierlichen Band oder Draht, das in einer spiralartigen Form gebogen ist. Die Materialien, die für Spiralfedern verwendet werden, variieren je nach Anwendung. Texturbänder, Edelstähle, Kohlenstoffstähle sowie Sonderwerkstoffe wie Kupfer-Legierungen finden Verwendung. Die Materialstärken bewegen sich typischerweise zwischen 0,10 und 1,5 mm." },
    { kind: "heading", level: 3, text: "Herstellung" },
    { kind: "paragraph", text: "Die Herstellung erfordert präzise Techniken und Fachwissen. Traditionelle Hersteller haben jahrelange Erfahrung in der Produktion und bieten maßgeschneiderte Lösungen an. Von der Einzelanfertigung bis zur Serienfertigung werden Spiralfedern nach den individuellen Anforderungen der Kunden hergestellt. Die Enden der Federn können verschiedene Formen haben, einschließlich Birnenloch, Bohrung, Lasche, Winkel, Öse oder auf spezielle Anfrage." },
    { kind: "heading", level: 2, text: "Anwendungen von Spiralfedern" },
    { kind: "paragraph", text: "Sie finden breite Anwendung in verschiedenen Branchen und bieten eine Vielzahl von Funktionen. Hier sind einige der Hauptanwendungen von Spiralfedern:" },
    { kind: "heading", level: 3, text: "1. Uhrenindustrie" },
    { kind: "paragraph", text: "In der Uhrenindustrie sind Spiralfedern eine Schlüsselkomponente für mechanische Uhrwerke. Unruh-Spiralfedern dienen als „Taktgeber“ und bestimmen die Ganggenauigkeit der Uhr. Spezielle Werkstoffe werden verwendet, um den Einfluss von Temperatur und Magnetismus auf die Genauigkeit der Uhr zu kompensieren." },
    { kind: "heading", level: 3, text: "2. Maschinenbau" },
    { kind: "paragraph", text: "Im Maschinenbau werden Spiralfedern als Rückstellelemente eingesetzt, um eine lineare Rückstellkraft zu erzeugen. Sie finden Verwendung in Anwendungen wie Pinolenhub und Magnetschaltern. Die Federn dienen als Ausgleichsfedern für kleinere Drehwinkel und bieten ein gleichmäßiges Rückstellmoment." },
    { kind: "heading", level: 3, text: "3. Elektroindustrie" },
    { kind: "paragraph", text: "Auch in der modernen Elektroindustrie kommen sie zum Einsatz, insbesondere in Magnetschaltern. Die Federn gewährleisten eine zuverlässige Rückstellung des Schalters und tragen zur Stabilität der elektrischen Komponenten bei." },
    { kind: "heading", level: 3, text: "4. Automobilindustrie" },
    { kind: "paragraph", text: "Die Automobilindustrie ist eine weitere wichtige Anwendung für Spiralfedern. Sie werden in verschiedenen Bereichen eingesetzt, darunter Fahrwerkskomponenten, Bremsen, Kupplungen und Lenksysteme. Spiralfedern bieten eine präzise und zuverlässige Federung, die zur Leistung und Sicherheit des Fahrzeugs beiträgt." },
    { kind: "heading", level: 2, text: "Spezialisierte Spiralfedern und ihre Eigenschaften" },
    { kind: "paragraph", text: "Neben den gängigen gibt es auch spezialisierte Varianten, die für bestimmte Anforderungen entwickelt wurden. Hier sind einige Beispiele:" },
    { kind: "heading", level: 3, text: "1. Bimetall-Federn" },
    { kind: "paragraph", text: "Bimetall-Federn werden für temperaturabhängige Stell- und Regelvorgänge eingesetzt. Sie finden Verwendung in Thermometern, Wärmereglern und Sicherheitsschaltern. Diese Federn nutzen die Eigenschaften unterschiedlicher Metalle, um präzise Bewegungen basierend auf Temperaturänderungen zu ermöglichen." },
    { kind: "heading", level: 3, text: "2. Ausgleichsfedern" },
    { kind: "paragraph", text: "Ausgleichsfedern dienen dazu, kleine Drehwinkel auszugleichen und eine gleichmäßige Rückstellung zu gewährleisten. Sie bieten eine präzise und zuverlässige Leistung in Anwendungen, bei denen eine genaue Rückstellung erforderlich ist." },
    { kind: "heading", level: 3, text: "3. Schwingungsgeber" },
    { kind: "paragraph", text: "Spiralfedern werden auch als Schwingungsgeber eingesetzt, insbesondere in Antrieben und Messwertsensoren. Sie bieten eine präzise und wiederholbare Schwingungsfrequenz, die in verschiedenen Anwendungen genutzt werden kann." },
    { kind: "heading", level: 2, text: "Fazit von Spiralfedern" },
    { kind: "paragraph", text: "Spiralfedern sind vielseitige Komponenten, die in verschiedenen Branchen weit verbreitet sind. Sie bieten eine präzise und zuverlässige Federung, Ausgleich und Rückstellung in einer Vielzahl von Anwendungen. Von der Uhrenindustrie bis zum Maschinenbau und der Elektroindustrie – sie spielen eine entscheidende Rolle bei der Gewährleistung von Präzision und Leistung. Durch die maßgeschneiderte Herstellung und Verwendung spezialisierter Varianten wie Bimetall-Federn können sie den spezifischen Anforderungen verschiedener Anwendungen gerecht werden." },
    { kind: "paragraph", text: "Vielleicht interessieren Sie sich auch für Zugfedern , Schenkelfedern oder Wellenfedern?" }
  ],
};
