// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/en/tailor-made-springs-customized-for-your-company/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const tailorMadeSpringsCustomizedForYourCompanyEN: PageEntry = {
  id: "post.flexibilitaet-und-qualitaet-federn-nach-mass-individuell-angefertigt-fuer-ihr-unternehmen",
  locale: "en",
  slug: "tailor-made-springs-customized-for-your-company",
  seo: {
    title: "Tailor-made springs - customized for your company | Dietz GmbH",
    description: "Welcome to our blog post about the benefits of customized springs for B2B customers! In this article, we will focus on the flexibility and quality of these springs and how they can",
  },
  type: "post",
  h1: "Tailor-made springs – customized for your company",
  intro: "Welcome to our blog post about the benefits of customized springs for B2B customers! In this article, we will focus on the flexibility and quality of these springs and how they can be customized for your company.",
  blocks: [
    { kind: "heading", level: 2, text: "Flexibility: Tailored to your requirements" },
    { kind: "paragraph", text: "A major advantage of custom-made springs is the flexibility they offer. In contrast to standard springs, customized springs can be adapted precisely to the specific requirements of your company. Whether you need springs for use in the automotive industry, mechanical engineering or medical technology, customized springs can be perfectly tailored to your needs." },
    { kind: "heading", level: 2, text: "Quality: Highest standards for optimum performance" },
    { kind: "paragraph", text: "With custom-made springs, quality comes first. Our springs are made from high-quality materials and are subject to strict quality controls to ensure optimum performance and durability. Each spring is individually tested to ensure that it meets the highest standards." },
    { kind: "heading", level: 2, text: "Customized production: Unique solutions for your company" },
    { kind: "paragraph", text: "Another major advantage of custom-made springs is the ability to create unique solutions for your company. Our experts work closely with you to understand your specific requirements and design customized springs. Whether you need a specific size, shape or load capacity, we can supply custom-made springs that perfectly match your requirements." },
    { kind: "heading", level: 2, text: "Summary" },
    { kind: "paragraph", text: "Customized springs offer B2B customers a number of advantages. Thanks to their flexibility, they can be adapted precisely to the individual requirements of your company. The high quality ensures that the springs function optimally and have a long service life. Individual production enables unique solutions that are specially tailored to your company." },
    { kind: "paragraph", text: "If you would like to know more about our customized springs and how they can support your business, please contact us. Our team of experts is on hand with help and advice." }
  ],
};
