// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/en/tension-springs-with-threaded-bolts/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const tensionSpringsWithThreadedBoltsEN: PageEntry = {
  id: "post.zugfedern-mit-gewindebolzen",
  locale: "en",
  slug: "tension-springs-with-threaded-bolts",
  seo: {
    title: "Tension springs with threaded bolts: A comprehensive overview | Dietz GmbH",
    description: "‍In the world of technical springs there are a variety of variants and designs. A particularly useful and versatile type of spring is the tension spring with a threaded bolt. In th",
  },
  type: "post",
  h1: "Tension springs with threaded bolts: A comprehensive overview",
  intro: "‍In the world of technical springs there are a variety of variants and designs. A particularly useful and versatile type of spring is the tension spring with a threaded bolt. In this article, we will look at this type of spring in detail and provide you with all the relevant information you need to make the right choice for your application.",
  blocks: [
    { kind: "heading", level: 2, text: "What are tension springs with threaded bolts?" },
    { kind: "paragraph", text: "Threaded stud tension springs are coil springs that are specifically designed to provide high tensile strength. They are usually made of high-quality round wire and have no turns between turns. At the ends of the spring there are threaded bolts that can have different shapes." },
    { kind: "paragraph", text: "There are a variety of possible uses for tension springs with threaded bolts. They are often used in applications where strong pulling force is required, such as in the automotive industry, mechanical engineering or medical technology. Due to their design and the presence of the threaded bolt, they offer high stability and can absorb large forces." },
    { kind: "heading", level: 2, text: "Various forms of tension springs with threaded bolts" },
    { kind: "paragraph", text: "There are different forms of threaded stud tension springs, each designed for specific applications. Here are some of the most common forms:" },
    { kind: "heading", level: 3, text: "1. Whole German eyelet" },
    { kind: "paragraph", text: "The whole German eyelet is the most commonly used form of threaded stud tension springs. It is characterized by its simple construction and high resilience. The German eyelet allows for easy attachment and provides a secure connection." },
    { kind: "heading", level: 3, text: "2. Double German eyelet" },
    { kind: "paragraph", text: "The double German eyelet is a variant of the full German eyelet in which two eyelets are attached to either end of the spring. This design provides improved stability and allows for even distribution of pulling force." },
    { kind: "heading", level: 3, text: "3. German eyelet raised on the side" },
    { kind: "paragraph", text: "The laterally raised German eyelet is a special form of the German eyelet in which the eyelet is attached to the side. This creates an angle that can be advantageous in certain applications." },
    { kind: "heading", level: 3, text: "4. Diagonally raised German eyelet" },
    { kind: "paragraph", text: "The diagonally raised German eyelet is similar to the laterally raised German eyelet, but in this case the eyelet is attached at an angle. This form of tension spring with threaded bolt is particularly suitable for applications where a specific angle is required." },
    { kind: "heading", level: 3, text: "5. 1/2 German eyelet" },
    { kind: "paragraph", text: "The 1/2 German eyelet is a modified form of the German eyelet in which the eyelet is only attached to one end of the spring. This design allows for easy attachment while still providing high tensile strength." },
    { kind: "heading", level: 3, text: "6. English eyelet" },
    { kind: "paragraph", text: "The English eye is another form of tension spring with threaded bolts. It is characterized by its simple construction and high resilience. The English eyelet allows for easy attachment and provides a secure connection." },
    { kind: "heading", level: 3, text: "7. Hook eye" },
    { kind: "paragraph", text: "The hook eye is a special form of tension springs with threaded bolts. It is characterized by its hook shape and allows for easy and secure attachment." },
    { kind: "heading", level: 3, text: "8. Hook eye raised to the side" },
    { kind: "paragraph", text: "The hook eye raised to the side is a variant of the hook eye in which the eye is attached to the side. This creates an angle that can be advantageous in certain applications." },
    { kind: "heading", level: 3, text: "9. Threaded bolt rolled up" },
    { kind: "paragraph", text: "In this design, the thread of the bolt is rolled into the spring. This creates a secure connection and high stability." },
    { kind: "heading", level: 3, text: "10. Threaded plug screwed in" },
    { kind: "paragraph", text: "The threaded plug is a special type of threaded bolt that is screwed into the spring. This design allows for easy attachment and provides a secure connection." },
    { kind: "heading", level: 3, text: "11. Screw tab screwed in" },
    { kind: "paragraph", text: "The screw tab is another variant of the threaded bolt. It screws into the spring and provides a secure attachment and connection." },
    { kind: "heading", level: 2, text: "Choosing the right tension spring with threaded bolts" },
    { kind: "paragraph", text: "When selecting the right threaded stud tension spring, it is important to consider the specific requirements of your application. Here are some important factors to consider when choosing:" },
    { kind: "list", ordered: true, items: ["Tensile Strength: Make sure the threaded stud tension spring you choose has the required tensile strength to meet the needs of your application.", "Dimensions: Check the dimensions of the spring, including diameter and length, to ensure it will fit your application.", "Eyelet Shape: Select the eyelet shape based on the specific needs of your application. Take into account the desired fastening type and the tensile force distribution.", "Surface finishing: In some cases it may be necessary to provide the tension spring with threaded bolts with a special surface finishing to prevent corrosion or wear. Make sure your chosen spring offers this option."] },
    { kind: "heading", level: 2, text: "Conclusion" },
    { kind: "paragraph", text: "Threaded stud extension springs are a versatile and useful type of spring that can be used in many different applications. Selecting the correct shape and construction is critical to meeting the needs of your application. Make sure you understand the specific needs of your application and consider the different options available. If necessary, you can contact an experienced engineering spring manufacturer or supplier for assistance in selecting the right threaded stud extension spring." }
  ],
};
