// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/en/the-invisible-force-everything-you-need-to-know-about-tension-springs/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const theInvisibleForceEverythingYouNeedToKnowAboutTensionSpringsEN: PageEntry = {
  id: "post.unsichtbare-kraft-spannfedern",
  locale: "en",
  slug: "the-invisible-force-everything-you-need-to-know-about-tension-springs",
  seo: {
    title: "The invisible force: everything you need to know about tension springs | Dietz GmbH",
    description: "Tension springs are a central element in the industry that is often overlooked, but represents an invisible force. In this article, we will learn everything you need to know about ",
  },
  type: "post",
  h1: "The invisible force: everything you need to know about tension springs",
  intro: "Tension springs are a central element in the industry that is often overlooked, but represents an invisible force. In this article, we will learn everything you need to know about tension springs, from how they work to the different areas of application.",
  blocks: [
    { kind: "heading", level: 2, text: "What are tension springs?" },
    { kind: "paragraph", text: "Tension springs are resilient components that are used to maintain a controlled tension or preload and hold components together. They are made of wire that is wound in a spiral or wave-like configuration. This configuration enables the spring to store and release energy when a force is applied to it." },
    { kind: "heading", level: 2, text: "How do tension springs work?" },
    { kind: "paragraph", text: "Tension springs work according to the principle of elastic deformation. When a tension spring is stretched or compressed, potential energy is stored in the spring. This energy is released when the force exerted on the spring decreases or is removed. This mechanism allows the spring to be used as a tensioning element to hold components firmly in position." },
    { kind: "heading", level: 2, text: "Types and applications of tension springs" },
    { kind: "paragraph", text: "There are different types of tension springs, depending on requirements and applications:" },
    { kind: "heading", level: 3, text: "Compression springs" },
    { kind: "paragraph", text: "Compression springs are used to maintain an axial compression force. They are often used in applications such as valves, punching machines and tools to hold parts in place or ensure damping." },
    { kind: "heading", level: 3, text: "Extension springs" },
    { kind: "paragraph", text: "Extension springs are known for their function as return springs. They are used in applications such as doors, gates and mechanical devices to generate a restoring force and return components to their original position." },
    { kind: "heading", level: 3, text: "Torsion springs" },
    { kind: "paragraph", text: "Torsion springs are used to generate torque. They are used in devices such as clocks, door locks and flap mechanisms to enable controlled rotation or turning movement." },
    { kind: "heading", level: 2, text: "Conclusion" },
    { kind: "paragraph", text: "Tension springs are an invisible force in industry and play a crucial role in securing and moving components. Whether it’s compression, tension or torsion, tension springs provide the necessary tension to ensure reliable performance. If you have any further questions about tension springs or require assistance in selecting the right spring for your application, please do not hesitate to contact us." }
  ],
};
