// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/umweltmanagementpreis-2024/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const umweltmanagementpreis2024DE: PageEntry = {
  id: "post.umweltmanagementpreis-2024",
  locale: "de",
  slug: "umweltmanagementpreis-2024",
  seo: {
    title: "Umweltmanagementpreis 2024 für Dietz GmbH | Dietz GmbH",
    description: "Umweltmanagementpreis 2024 für Dietz GmbH",
  },
  type: "post",
  h1: "Umweltmanagementpreis 2024 für Dietz GmbH",
  blocks: [
    { kind: "heading", level: 2, text: "Umweltmanagementpreis 2024 für Dietz GmbH" },
    { kind: "paragraph", text: "Mit Stolz dürfen wir verkünden, dass wir sowohl den Umweltmanagementpreis 2023 mit der besten Strategie für eine nachhaltige Unternehmensentwicklung als auch den Umweltmanagementpreis 2024 für die beste EMAS-Umwelterklärung gewonnen haben! 🏆" },
    { kind: "paragraph", text: "Dieser Erfolg ist das Ergebnis unserer kontinuierlichen Bemühungen, nachhaltige Prozesse zu implementieren, den CO₂-Ausstoß zu reduzieren und Verantwortung für die Gegenwart und Zukunft zu übernehmen. Alle Dietz Mitarbeitende arbeiten gemeinsam daran, innovative Lösungen für eine nachhaltige Zukunft zu entwickeln und auch umzusetzen, und diese Auszeichnungen bestätigen unser Engagement." },
    { kind: "paragraph", text: "Stellvertretend für alle beteiligten Kolleginnen und Kollegen der Dietz GmbH durften wir am 05.11.2024 in Wien den Preis entgegennehmen." },
    { kind: "paragraph", text: "Vielen Dank an die Veranstalter, das Bundesministerium für Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz (BMUV), das Bundesministerium für Klimaschutz, Umwelt, Energie, Mobilität, Innovation & Technologie und die gesamte Fachjury!" },
    { kind: "paragraph", text: "Ein großes Dankeschön an alle Mitarbeitenden die die Dietz GmbH auf diesem Weg unterstützt haben und weiterhin unterstützen werden!" },
    { kind: "paragraph", text: "Nachhaltigkeit ist für Dietz eine wichtige Managementaufgabe, mit einem gemeinsamen Nachhaltigkeitsverständnis sowie strategischen und operativen Zielen, die kontinuierlich geprüft und bewertet werden." },
    { kind: "paragraph", text: "Aus Sicht der Jury ist die EMAS-Umwelterklärung im Nachhaltigkeitsbericht sehr gut als solche erkennbar und beschrieben. Der Zusammenhang zwischen den Umweltaspekten und -auswirkungen sowie Maßnahmen ist klar und nachvollziehbar dargestellt. Bei den Umweltleistungen ist die Verbesserung eindeutig festgehalten und ersichtlich. Darüber hinaus ist die Transparenz der Umweltleistung und der nachhaltigen Unternehmensentwicklung vorbildlich." },
    { kind: "paragraph", text: "Offizielle Pressemitteilung: https://www.emas.de/emas-wettbewerbe" },
    { kind: "paragraph", text: "https://www.bmuv.de/pressemitteilung/umweltmanagement-preis-2024-zeichnet-sechs-deutsche-organisationen-fuer-beispielhafte-umweltleistungen-aus" },
    { kind: "image", src: "/images/live/Preis-scaled.jpeg", alt: "Umweltmanagementpreis 2024 für Dietz GmbH", width: 1014, height: 1280 }
  ],
};
