// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/umweltpakt-bayern-2-2-2-2/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const umweltpaktBayern2222DE: PageEntry = {
  id: "post.umweltpakt-bayern-2-2-2-2",
  locale: "de",
  slug: "umweltpakt-bayern-2-2-2-2",
  seo: {
    title: "Hightech live! im Haus DIETZ – | Dietz GmbH",
    description: "Hightech live! im Haus DIETZ –",
  },
  type: "post",
  h1: "Hightech live! im Haus DIETZ –",
  blocks: [
    { kind: "heading", level: 2, text: "Hightech live! im Haus DIETZ –" },
    { kind: "paragraph", text: "Online-Veranstaltung für angehende Azubis ein voller Erfolg" },
    { kind: "paragraph", text: "Pandemiebedingt musste am 18. November 2020 der Hightech live! -Projekttag bei DIETZ entfallen, bei dem interessierte Schülerinnen und Schüler einen Einblick in die verschiedenen Ausbildungsberufe erhalten hätten. Kurzerhand wurde die Veranstaltung stattdessen „online“ geschalten, sodass sich elf junge Talente aus den Mittel- und Realschulen der Region über die technischen Berufe und das Arbeitsumfeld bei DIETZ per Live-Video-Übertragung informieren konnten." },
    { kind: "paragraph", text: "Von drei bestehenden Azubis – Eloise, Sebastian und Bastian – wurden die Berufsbilder Fachlagerist/-in, Werkzeugmechaniker/-in und Elektriker/-in live und „in Action“ vorgestellt." },
    { kind: "paragraph", text: "Darüber hinaus standen Ausbildungsleiter Michael Wagner und Personalassistentin Johanna Roth Rede und Antwort." },
    { kind: "paragraph", text: "Trotz Krise war Hightech live! also ein voller Erfolg und kam dem Ziel der Bildungsinitiative Technik – Zukunft in Bayern 4.0 nach, junge Menschen für Technik und Naturwissenschaft zu begeistern. Auch Geschäftsführer Matthias Dietz wusste die Möglichkeiten der Digitalisierung zu schätzen: „Wir bedauern, dass wir die Schülerinnen und Schüler nicht wie geplant zu uns in den Betrieb einladen konnten. Durch die Online-Veranstaltung konnten wir den Jugendlichen trotzdem zeigen, dass unsere Ausbildungsberufe abwechslungsreich sind, Spaß machen und attraktive berufliche Perspektiven bieten.“" },
    { kind: "paragraph", text: "Freie Ausbildungsplätze 2021" },
    { kind: "paragraph", text: "Wir haben noch freie Plätze für eine Ausbildung mit Start im Herbst 2021 zu vergeben. Klingt interessant? Dann schau hier vorbei: www.dietz.eu/karriere und www.dietz.eu/karriere/schueler/" }
  ],
};
