// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/umweltpolitik-in-der-praxis-leben-und-mit-ideen-gemeinsam-vorankommen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const umweltpolitikInDerPraxisLebenUndMitIdeenGemeinsamVorankommenDE: PageEntry = {
  id: "post.umweltpolitik-in-der-praxis-leben-und-mit-ideen-gemeinsam-vorankommen",
  locale: "de",
  slug: "umweltpolitik-in-der-praxis-leben-und-mit-ideen-gemeinsam-vorankommen",
  seo: {
    title: "Umweltpolitik in der Praxis leben und mit Ideen gemeinsam vorankommen | Dietz GmbH",
    description: "Umweltpolitik in der Praxis leben und mit Ideen gemeinsam vorankommen",
  },
  type: "post",
  h1: "Umweltpolitik in der Praxis leben und mit Ideen gemeinsam vorankommen",
  blocks: [
    { kind: "heading", level: 2, text: "Umweltpolitik in der Praxis leben und mit Ideen gemeinsam vorankommen" },
    { kind: "paragraph", text: "Unter diesem Motto steht die zweite Dietz Umweltwoche vom 06.03.-10.03.2023." },
    { kind: "paragraph", text: "Alle Mitarbeitenden sind herzlich dazu eingeladen sich zu unterschiedlichen Themenbereichen rund um das Umweltmanagement im Unternehmen zu informieren." },
    { kind: "paragraph", text: "Die Themen Energiemanagement, Abfallmanagement, Biodiversität stehen im Fokus der Umweltwoche." },
    { kind: "paragraph", text: "Zudem gibt es auch eine interne Schulung für alle Mitarbeitenden zum Thema „EMAS“ und eine dazugehörige Besichtigung der Wanderausstellung." },
    { kind: "paragraph", text: "Des Weiteren werden die Umweltmanagementziele für 2023-2025 erläutert." },
    { kind: "paragraph", text: "Die zukünftige Generation für das Thema Umweltmanagement zu sensibilisieren ist uns ein großes Anliegen. In diesem Zusammenhang arbeiten wir bundesländerübergreifend mit verschiedenen Schulen zusammen und führen unterschiedliche Projekte zusammen mit den Schülern durch." },
    { kind: "paragraph", text: "Wir freuen uns auf das Feedback zur zweiten Dietz internen Umweltwoche." },
    { kind: "image", src: "/images/live/Maschinen-Anlagen-Fueherer.jpg", alt: "Umweltpolitik in der Praxis leben und mit Ideen gemeinsam vorankommen", width: 1600, height: 843 }
  ],
};
