// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/umzug-zum-jahresende/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const umzugZumJahresendeDE: PageEntry = {
  id: "post.umzug-zum-jahresende",
  locale: "de",
  slug: "umzug-zum-jahresende",
  seo: {
    title: "Umzug zum Jahresende | Dietz GmbH",
    description: "Umzug zum Jahresende",
  },
  type: "post",
  h1: "Umzug zum Jahresende",
  blocks: [
    { kind: "heading", level: 2, text: "Umzug zum Jahresende" },
    { kind: "heading", level: 3, text: "Firmenentwicklung" },
    { kind: "paragraph", text: "Das gesamt Jahr über haben wir an dieser Stelle vom Baufortschritt unserer neuen Halle in Sonneberg berichtet.Pünktlich zur Dezember-Ausgabe von DIETZ intern ist es soweit, und wir können uns auf den Einzug freuen. Obwohl sich im Herbst eine kurze Verzögerung im Projektplan ergeben hatte, wird dies auf den Einzugstermin und die Inbetriebnahme der neuen Arbeitsstätte keine Auswirkung haben. Die Halle und die darin liegenden Büroräume sind nun vollständig fertiggestellt, Mitte November wurde mit der Installation von Heizung, Lüftung und Elektrik begonnen. Erste Maschinen werden im Dezember den Standort wechseln, und der eigentliche Umzug steht in den Wochen 50 und 51 an, sodass zum Jahresbeginn 2017 alles für die Abteilung Montagetechnik fertigungsbereit sein wird. Nachdem wir verschiedene Hallenlayouts mit dem Expertenteam vom Fraunhofer Institut entwickelt hatten, haben wir uns nun für ein finales Schema entschieden, das die Wege in der Halle optimiert und dafür die ideale Positionierung der Maschinen festlegt. Das Ergebnis kann sich sehen lassen und ab kommendem Jahr auch in der Praxis bewähren. Bei der internen Weihnachtsfeier am 22.12., zu der wir die gesamte Belegschaft herzlich nach Sonneberg einladen, können sich alle ein eigenes Bild von der neuen Produktionsund Lagerhalle machen." }
  ],
};
