// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/unternehmen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const unternehmenDE: PageEntry = {
  id: "post.unternehmen",
  locale: "de",
  slug: "unternehmen",
  seo: {
    navLabel: "Unternehmen",
    title: "Das Unternehmen Dietz Federn",
    description: "Das Unternehmen Dietz Federn",
  },
  type: "post",
  h1: "Das Unternehmen Dietz Federn",
  blocks: [
    { kind: "heading", level: 2, text: "Leistungsfähig und kompetent – seit 90 Jahren" },
    { kind: "heading", level: 3, text: "Wir investieren kontinuierlich in modernste Technologie" },
    { kind: "paragraph", text: "Gegründet 1928 in Neustadt bei Coburg, ist die Dietz GmbH einer der führenden Hersteller von technischen Präzisionsfedern und Drahtbiegeteilen. Als mittelständisches, inhabergeführtes Unternehmen mit 170 Beschäftigten beliefert Dietz namhafte und internationale Kunden aus den verschiedensten Industriezweigen, wie etwa der Automobil- und Elektroindustrie oder der Haus- und Medizintechnik. Das umfassendes Spezialisten-Know-how und eine sorgfältige Fertigung in Hightech-Produktionsanlagen sorgen für maßgeschneiderte Federlösungen von höchster Präzision und Qualität." },
    { kind: "paragraph", text: "Um erfolgreich zu sein, ist der Einsatz modernster Technologie unverzichtbar. Wir haben uns den Herausforderungen der Märkte stets gestellt und technologisch Schritt gehalten – mit Erfolg:" },
    { kind: "paragraph", text: "Heute sind wir eine Federnfabrik mit einem innovativen Produktportfolio – ein leistungsfähiger und kompetenter Partner in allen Bereichen der Federnherstellung." },
    { kind: "heading", level: 3, text: "Höchste Qualität und Präzision" },
    { kind: "paragraph", text: "Die Federnherstellung erfordert höchste Präzision, um alle Anforderungen an komplexe Strukturen und deren Funktionalität zu erfüllen. Aufgrund steigender Qualitätsansprüche werden Werkstoffe und Produkte bei uns ständig weiterentwickelt. Ihre Funktionsfähigkeit wird durch permanente Qualitätsprüfungen abgesichert. Die Prüfungsergebnisse stellen wir Ihnen selbstverständlich gerne zur Verfügung." },
    { kind: "paragraph", text: "Bei der Herstellung von Federn, Drahtbiegeteilen und Stanz-Umformteilen garantieren wir Ihnen, dass unsere Artikel halten, was sie versprechen – dank modernster Maschinen, hochwertiger Materialien, eigener Werkzeugfertigung, qualifiziertem Personal, einer permanenten Qualitätskontrolle und nicht zuletzt dank einer Lehrwerkstatt mit 15–20 Auszubildenden." },
    { kind: "heading", level: 3, text: "Flexible Logistik mit kurzen Lieferzeiten" },
    { kind: "paragraph", text: "Höchste Versorgungssicherheit und ein möglichst geringer Abwicklungsaufwand für unsere Kunden sind unser Ziel. Dies verfolgen wir mit unserem datenbankgestützten Lagerhaltungssystem – im Rohmaterial-Lager wie auch im Fertigteil-Lager. Dank unserer schlanken Strukturen und Prozesse sind wir in der Lage, äußerst flexibel auf Ihre logistischen Ansprüche zu reagieren." },
    { kind: "paragraph", text: "Ganz gleich, ob Sie Just-in-Time-, Just-in-Sequence-, Kanban-Lösungen, DFÜ-Abrufe oder Konsignationslager bevorzugen: Wir finden für Sie die optimale logistische Lösung bei der Lieferung Ihrer Federn, Drahtbiegeteile, hybriden Baugruppen und vieles mehr." },
    { kind: "image", src: "/images/live/dietz_aussen-1200x375.jpg", alt: "Firmengebäude Dietz", width: 1200, height: 375 }
  ],
};
