// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/zugfedern-mit-oesen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const zugfedernMitOesenDE: PageEntry = {
  id: "post.zugfedern-mit-oesen",
  locale: "de",
  slug: "zugfedern-mit-oesen",
  seo: {
    title: "Alles Wissenswerte über Zugfedern mit Ösen | Dietz GmbH",
    description: "Die Verwendung von Zugfedern mit Ösen ist in vielen technischen Anwendungen weit verbreitet. Diese speziellen Federn werden häufig in verschiedenen Industriezweigen wie der Automob",
  },
  type: "post",
  h1: "Alles Wissenswerte über Zugfedern mit Ösen",
  intro: "Die Verwendung von Zugfedern mit Ösen ist in vielen technischen Anwendungen weit verbreitet. Diese speziellen Federn werden häufig in verschiedenen Industriezweigen wie der Automobilindustrie, dem Maschinenbau und der Elektroindustrie eingesetzt.",
  blocks: [
    { kind: "heading", level: 2, text: "Was sind Zugfedern mit Ösen?" },
    { kind: "paragraph", text: "Zugfedern sind Schraubenfedern, die in der Regel aus Runddraht gefertigt werden. Sie zeichnen sich durch ihre hohe Zugfestigkeit aus und werden oft für Anwendungen verwendet, bei denen eine Zugkraft erzeugt werden muss. Die Ösen an den Enden der Zugfedern dienen als Befestigungspunkte, um die Feder an andere Komponenten oder Strukturen anzuschließen. Es gibt verschiedene Arten von Ösen, die für Zugfedern verwendet werden können, darunter die deutsche Öse, die englische Öse, Hakenösen und mehr." },
    { kind: "heading", level: 2, text: "Verschiedene Ösenformen für Zugfedern" },
    { kind: "paragraph", text: "Es gibt eine Vielzahl von Ösenformen, die für Zugfedern nach DIN EN 13906-2:2013 spezifiziert sind. Jede Form hat ihre eigenen Eigenschaften und Anwendungsbereiche. Hier sind einige der gängigsten Ösenformen für Zugfedern:" },
    { kind: "heading", level: 3, text: "1/1 Deutsche Öse" },
    { kind: "paragraph", text: "Die 1/1 deutsche Öse ist die gängigste Ösenform für Zugfedern. Sie hat eine spezifische Abstandsanforderung (Lh), die zwischen 0,8 und 1,1 mal dem inneren Windungsdurchmesser (Di) liegen muss. Zusätzlich kann die Ösenöffnungsweite (m) angegeben werden." },
    { kind: "heading", level: 3, text: "1/1 Doppelte deutsche Öse" },
    { kind: "paragraph", text: "Die 1/1 doppelte deutsche Öse ist ähnlich wie die 1/1 deutsche Öse, jedoch mit doppelter Ösenanzahl. Auch hier muss der Abstand (Lh) zwischen 0,8 und 1,1 mal dem inneren Windungsdurchmesser (Di) liegen." },
    { kind: "heading", level: 3, text: "1/1 Deutsche Öse seitlich hochgestellt" },
    { kind: "paragraph", text: "Die 1/1 deutsche Öse seitlich hochgestellt hat eine ähnliche Form wie die 1/1 deutsche Öse, jedoch ist die Öse seitlich angebracht. Der Abstand (Lh) kann hier dem inneren Windungsdurchmesser (Di) entsprechen, und die Ösenöffnungsweite (m) kann angegeben werden." },
    { kind: "heading", level: 3, text: "1/1 Doppelte deutsche Öse seitlich hochgestellt" },
    { kind: "paragraph", text: "Die 1/1 doppelte deutsche Öse seitlich hochgestellt hat die gleiche Form wie die 1/1 deutsche Öse seitlich hochgestellt. Es gibt keine spezifischen Zusatzangaben für diese Ösenform." },
    { kind: "heading", level: 3, text: "1/1 Deutsche Öse schräg hochgestellt" },
    { kind: "paragraph", text: "Die 1/1 deutsche Öse schräg hochgestellt hat eine schräge Positionierung der Öse. Die Ösenöffnungsweite (m) kann angegeben werden." },
    { kind: "heading", level: 3, text: "1/2 Deutsche Öse" },
    { kind: "paragraph", text: "Die 1/2 deutsche Öse hat eine spezifische Abstandsanforderung (Lh), die zwischen 0,55 und 0,8 mal dem inneren Windungsdurchmesser (Di) liegen muss. Zusätzlich kann die Ösenöffnungsweite (m) angegeben werden." },
    { kind: "heading", level: 3, text: "Englische Öse, Hakenöse und weitere Ösenformen" },
    { kind: "paragraph", text: "Neben den deutschen Ösen gibt es auch andere Ösenformen für Zugfedern wie die englische Öse, Hakenösen und weitere spezielle Formen. Diese haben jeweils ihre eigenen Eigenschaften und Einsatzbereiche." },
    { kind: "heading", level: 2, text: "Einsatzbereiche von Zugfedern mit Ösen" },
    { kind: "paragraph", text: "Zugfedern mit Ösen finden in vielen verschiedenen Anwendungen Verwendung. Sie können als Zugfederstränge eingesetzt werden, um Schläuche oder Kabel vor mechanischer Beanspruchung zu schützen. Die Ösen dienen dabei als Befestigungspunkte." },
    { kind: "paragraph", text: "Darüber hinaus können Zugfedern mit Ösen in verschiedenen Industriezweigen eingesetzt werden, darunter die Automobilindustrie, der Maschinenbau, die Elektroindustrie, die erneuerbare Energie- und Umwelttechnologie, die Medizin- und Chemietechnik und vieles mehr. Die Verwendung von Zugfedern mit Ösen ermöglicht eine zuverlässige und sichere Befestigung in vielen technischen Anwendungen." },
    { kind: "heading", level: 2, text: "Fertigung und Veredelung von Zugfedern mit Ösen" },
    { kind: "paragraph", text: "Die Herstellung von Zugfedern mit Ösen erfolgt in der Regel auf CNC-Maschinen, um eine konstante Länge und Präzision zu gewährleisten. Optische Kontroll- und Sortiersysteme wie Kameras und Laser werden eingesetzt, um die Qualität der Zugfedern zu überprüfen." },
    { kind: "paragraph", text: "Zugfedern mit Ösen können sowohl kaltgesetzt als auch warmgesetzt geliefert werden, abhängig von den Anforderungen der Anwendung. Die Wärmebehandlung erfolgt bei Eckel Federn temperaturüberwacht, um eine gleichbleibende Qualität sicherzustellen." },
    { kind: "paragraph", text: "Für Zugfedern mit Ösen sind verschiedene Oberflächenveredelungen möglich, darunter Beizen, Cadmieren, KTL-Beschichtung, Lackieren, Passivieren, Phosphatieren, Ölen, Pulverbeschichten, Verchromen, Vergolden, Vernickeln, Verzinken, Chromatieren. Auch verschiedene Oberflächenbearbeitungen wie Elektropolieren, Gleitschleifen, Härten und Anlassen, Kugelstrahlen und Ölen, Sandstrahlen oder Trovalisieren können durchgeführt werden." },
    { kind: "heading", level: 2, text: "Fazit" },
    { kind: "paragraph", text: "Zugfedern mit Ösen sind in vielen technischen Anwendungen unverzichtbar. Die verschiedenen Ösenformen ermöglichen eine sichere Befestigung und vielseitige Einsatzmöglichkeiten. Die Herstellung erfolgt auf CNC-Maschinen und bietet eine hohe Präzision und Qualität. Durch verschiedene Oberflächenveredelungen und -bearbeitungen können Zugfedern mit Ösen an die spezifischen Anforderungen der Anwendung angepasst werden." },
    { kind: "paragraph", text: "Wenn Sie auf der Suche nach einem Hersteller oder Lieferanten von Zugfedern mit Ösen sind, können Sie sich an Fachleute wie uns wenden. Wir bieten maßgeschneiderte Lösungen für Ihre Anforderungen und unterstützen Sie bei der Auswahl der richtigen Ösenform und Oberflächenveredelung. Kontaktieren Sie uns noch heute für weitere Informationen und eine individuelle Beratung." }
  ],
};
