// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/kunststofftechnik/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const kunststofftechnikDE: PageEntry = {
  id: "product.kunststofftechnik",
  locale: "de",
  slug: "kunststofftechnik",
  seo: {
    navLabel: "Kunststofftechnik",
    title: "Kunststofftechnik | Dietz GmbH",
    description: "Kunststofftechnik",
  },
  type: "post",
  h1: "Kunststofftechnik",
  blocks: [
    { kind: "image", src: "/images/live/DTZ_Zahnrad_Polyoxymethylen.jpg", alt: "Zahnrad Polyoxymethylen", width: 800, height: 640 },
    { kind: "heading", level: 2, text: "Kunststofftechnik" },
    { kind: "paragraph", text: "Mit modernster Technologie und langjähriger Erfahrung bieten wir unseren Kunden maßgeschneiderte Lösungen in den Bereichen Kunststoffspritzguss, und 3D-Druck. Dabei legen wir größten Wert auf Qualität, Präzision und Innovation." },
    { kind: "image", src: "/images/live/DTZ_Hebel-_Polyamid.jpg", alt: "Hebel aus Polyamid", width: 800, height: 640 },
    { kind: "paragraph", text: "Unser Leistungsspektrum umfasst die gesamte Prozesskette der Kunststoffverarbeitung – angefangen von der Konzeption und Entwicklungsunterstützung individueller Bauteile bis hin zur Serienfertigung. Für die Umsetzung Ihrer Projekte stehen uns hochmoderne Produktionsanlagen sowie ein qualifiziertes und engagiertes Team zur Verfügung. Wir setzen auf kontinuierliche Weiterbildung unserer Mitarbeiter, um immer auf dem neuesten Stand der Technik zu sein." },
    { kind: "list", items: ["Zahnrad aus Polyoxymethylen Zahnrad aus Polyoxymethylen (POM) zur Kraftübertragung im Automobilbereich.", "Hebel aus Polyamid (PA) Hebel aus Polyamid (PA) mit einem Glasfaseranteil von 30% zur Weiterverarbeitung in Schaltersystemen. Diese Bauteile übertragen Bewegungen in komplexen Baugruppen."] },
    { kind: "heading", level: 3, text: "Kunststofftechnik von Dietz" },
    { kind: "paragraph", text: "Unser Anspruch ist es, maßgeschneiderte Lösungen zu liefern, die höchsten Qualitäts- und Sicherheitsstandards entsprechen. Dabei legen wir großen Wert auf Nachhaltigkeit und Umweltverträglichkeit. Wir arbeiten mit ressourcenschonenden und recyclingfähigen Materialien und setzen auf effiziente Produktionsprozesse, um den ökologischen Fußabdruck unserer Produkte zu minimieren." },
    { kind: "paragraph", text: "Unsere langjährige Erfahrung und unser umfangreiches Know-how ermöglichen es uns, auch anspruchsvolle Projekte erfolgreich umzusetzen. Ob Prototypen, Einzelstücke oder Großserien – wir realisieren Ihre Vorstellungen präzise und termintreu. Dabei stehen wir Ihnen von der Idee bis zum fertigen Produkt als erfahrener Partner zur Seite und begleiten Sie in jedem Schritt." },
    { kind: "paragraph", text: "Unsere Kunden kommen aus den unterschiedlichsten Branchen, darunter Automobilindustrie, Medizintechnik, Elektro- und Elektronikindustrie, Verpackungsindustrie und viele mehr. Dank unserer Vielseitigkeit können wir individuelle Lösungen für jede Anwendung bieten." },
    { kind: "paragraph", text: "Die Dietz GmbH steht für höchste Qualität, technische Kompetenz und zufriedene Kunden. Wenn Sie einen zuverlässigen Partner für Ihre Kunststoffprojekte suchen, sind Sie bei uns genau richtig. Kontaktieren Sie uns gerne für eine persönliche Beratung und gemeinsame Planung Ihres Projekts. Wir freuen uns auf die Zusammenarbeit mit Ihnen." },
    { kind: "heading", level: 2, text: "Ihre Anfrage" },
    { kind: "paragraph", text: "Übermitteln Sie uns Ihre Anforderungen für ein Bauteil. Senden Sie uns gegebenenfalls erste Konstruktionszeichnungen. Wir behandeln Ihre Daten absolut vertraulich und speichern diese nur zur Dauer der Bearbeitung Ihrer Anfrage." },
    { kind: "paragraph", text: "Diese Anfrage ist für Sie selbstverständlich unverbindlich." }
  ],
};
