// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/produkte/zugfedern/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const produkteZugfedernDE: PageEntry = {
  id: "product.produkte-zugfedern",
  locale: "de",
  slug: "produkte/zugfedern",
  seo: {
    navLabel: "Zugfedern",
    title: "Zugfedern: Langlebigkeit & Flexibilität | Dietz GmbH",
    description: "Zugfedern: Langlebigkeit & Flexibilität",
  },
  type: "post",
  h1: "Zugfedern: Langlebigkeit & Flexibilität",
  cta: { kind: "typeform", typeformId: "01HHYPGYGQFR0BRFHV2WWR2ZEF", label: "Jetzt unverbindlich Kontakt mit uns aufnehmen" },
  blocks: [
    { kind: "heading", level: 2, text: "Alles, was Sie über Zugfedern wissen müssen" },
    { kind: "paragraph", text: "Zugfedern sind ein wesentlicher Bestandteil vieler industrieller Anwendungen, insbesondere in Bereichen wie der Automobilindustrie, der Elektrotechnik, der Feinmechanik und der Gebäudetechnik. Sie werden verwendet, um einer Axialkraft entgegenzuwirken und die Verlängerung der Feder zu kontrollieren. In diesem Artikel werden wir uns eingehend mit Zugfedern befassen und Ihnen alles Wichtige über ihre Funktionsweise, Abmessungen, Materialien, Anwendungen und Vorteile erklären." },
    { kind: "heading", level: 3, text: "Funktionsweise von Zugfedern" },
    { kind: "paragraph", text: "Zugfedern wirken einer Axialkraft entgegen, die auf die Verlängerung der Feder gerichtet ist. Der Federkörper besteht aus ineinander liegenden Windungen, die eine Vorspannkraft erzeugen. Zur Kraftübertragung werden die Federenden mit Ösen, Haken, Stopfen oder anderen Sonderformen ausgestattet. Die Wahl des richtigen Federendes hängt von den Anforderungen der Anwendung ab." },
    { kind: "paragraph", text: "Die Vorspannkraft einer Zugfeder ist abhängig vom Fertigungsverfahren, dem Wickeln und Winden. Hohe Vorspannkräfte ermöglichen es, die Baulänge der Feder zu reduzieren, haben jedoch Auswirkungen auf die Federkennlinie. Wenn die Belastung geringer ist als die Vorspannkraft, bleibt die Zugfeder ungedehnt." },
    { kind: "heading", level: 3, text: "Abmessungen von Zugfedern" },
    { kind: "paragraph", text: "Zugfedern sind in verschiedenen Abmessungen erhältlich, um den Anforderungen unterschiedlicher Anwendungen gerecht zu werden. Der Drahtdurchmesser kann von 0,1 mm bis zu 5,26 mm variieren. Je nach Bedarf können Zugfedern mit unterschiedlichen Längen hergestellt werden. Die Federn können auch gekürzt und montiert werden, um den spezifischen Anforderungen gerecht zu werden." },
    { kind: "heading", level: 3, text: "Materialien für Zugfedern" },
    { kind: "paragraph", text: "Für die Herstellung von Zugfedern werden verschiedene Materialien verwendet. Die gängigsten Materialien sind 1.1200 Federstahldraht und 1.4310 Federstahldraht rostfrei V2a. Je nach statischer oder dynamischer Belastung können verschiedene Drahtsorten ausgewählt werden. Es ist auch möglich, Zugfedern aus Werkstoffen nach DIN EN 10270 und EN ISO 6931 herzustellen." },
    { kind: "heading", level: 3, text: "Anwendungen von Zugfedern" },
    { kind: "paragraph", text: "Zugfedern finden in verschiedenen Branchen und Anwendungen Anwendung. In der Automobilindustrie werden sie beispielsweise in Scheinwerfern, Sitzen, Türverriegelungen und Kofferraumdeckeln eingesetzt. In der Elektrotechnik werden Zugfedern in Schaltern, Relais und Schaltern verwendet. In der Feinmechanik finden sie Anwendung in Uhren, Kameras und Messgeräten. In der Gebäudetechnik werden Zugfedern in Türen, Fenstern und Rollläden eingesetzt. Darüber hinaus werden Zugfedern auch in Konsumgütern wie Spielzeug, Möbeln und Sportgeräten verwendet." },
    { kind: "heading", level: 3, text: "Vorteile von Zugfedern" },
    { kind: "paragraph", text: "Zugfedern bieten verschiedene Vorteile, die sie zu einer beliebten Wahl für viele Anwendungen machen. Ihre linearen Kennlinien ermöglichen eine präzise Kraftübertragung und Kontrolle. Durch die Verwendung verschiedener Ösenformen können Zugfedern flexibel an verschiedene Anforderungen angepasst werden. Die Vorspannung einer Zugfeder spart Baulänge und ermöglicht eine effizientere Nutzung des verfügbaren Raums. Zugfedern können auch als Federstränge verwendet werden, um kurzfristige Zwischenlösungen zu realisieren oder als Knickschutz für Schläuche und Kabel zu dienen." },
    { kind: "heading", level: 3, text: "Bestellung und Herstellung von Zugfedern" },
    { kind: "paragraph", text: "Zugfedern können nach spezifischen Anforderungen bestellt und hergestellt werden. Je nach Bedarf können Zugfedern mit verschiedenen Ösen, Haken oder Stopfen ausgestattet werden. Die Bestellung von Zugfedern erfolgt in der Regel gemäß den Standards DIN 2097 oder nach Kundenvorgabe. Die Herstellung erfolgt aus hochwertigem Federstahldraht und kann sowohl angelassen als auch roh blank oder oberflächenbehandelt nach Kundenvorgabe erfolgen." },
    { kind: "paragraph", text: "Wir haben langjährige Erfahrung in der Herstellung und Anpassung von Zugfedern für verschiedene Branchen und Anwendungen. Unser Sortiment umfasst Zugfedern mit verschiedenen Abmessungen, Materialien und Enden. Wir bieten auch maßgefertigte Lösungen an und unterstützen unsere Kunden bei der Auswahl der richtigen Zugfedern für ihre spezifischen Anforderungen." },
    { kind: "heading", level: 2, text: "Sonderformen von Ösen bei Zugfedern" },
    { kind: "paragraph", text: "Trompetenanbindungen und Montagehilfen für Zugfedern finden einen wachsenden Anwendungsbereich – mit diesem Lösungsansatz beschäftigen wir uns bereits seit vielen Jahren." },
    { kind: "paragraph", text: "Wir fertigen unser Zugfedernsortiment mit deutschen und englischen Ösen von 0,25 mm bis 4,00 mm Drahtdurchmesser. Bei Bedarf fertigen wir auch mit Sonderösen und Ösenformen nach speziellen Anforderungen im Drahtdurchmesser-Bereich von 0,20 mm bis 4,00 mm." },
    { kind: "paragraph", text: "Alle technischen Federn fertigen wir auf Anfrage auch in kleineren Losgrößen. Für alle Produkte werden auch Sonderverpackungen angeboten. Wir verfügen über einen eigenen Werkzeugbau und als Ihr Entwicklungspartner leisten wir für Sie auch individuelle Berechnungen." }
  ],
};
