// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/en/products/prototype-and-sample-development/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const productsPrototypeAndSampleDevelopmentEN: PageEntry = {
  id: "product.produkte-prototypen-und-musterbau",
  locale: "en",
  slug: "products/prototype-and-sample-development",
  seo: {
    navLabel: "Prototype & sample construction",
    title: "Prototype and sample development | Dietz GmbH",
    description: "Prototype and Pattern Making: A Comprehensive Guide",
  },
  type: "post",
  h1: "Prototype and sample development",
  intro: "Prototype and Pattern Making: A Comprehensive Guide",
  blocks: [
    { kind: "paragraph", text: "Prototype and pattern making is a crucial step in product development. It allows companies to translate their ideas into physical forms and test their functionality before moving into mass production. In this comprehensive guide, we’ll delve into various aspects of prototype and pattern making, providing insights into different options and technologies." },
    { kind: "heading", level: 2, text: "What is a Prototype?" },
    { kind: "paragraph", text: "A prototype is a physical representation of a product developed to assess design, functionality, and material selection. It’s often used as a template for mass production. A well-designed prototype enables companies to identify potential issues early on and make necessary changes, thereby saving costs and time in later production phases." },
    { kind: "heading", level: 2, text: "Why is Pattern Making Important?" },
    { kind: "paragraph", text: "Pattern making is a crucial step in product development as it allows companies to materialize their ideas and test their functionality. Through pattern making, potential issues can be identified and rectified before the product enters mass production. This saves time and costs for companies and ultimately enhances the quality of the end product." },
    { kind: "heading", level: 2, text: "Laser-Generated Pattern Parts" },
    { kind: "paragraph", text: "Laser-generated pattern parts are a modern technology enabling the layer-by-layer construction of components from powdered metallic series materials. This process is controlled by lasers that fuse the powder material into the desired contour. One advantage of this technology is the accurate translation of computer-generated 3D/CAD models into their physical forms. Moreover, excess powder material is reclaimed in this process and reused for further productions." },
    { kind: "heading", level: 2, text: "Technical Springs in Pattern Making" },
    { kind: "paragraph", text: "Technical springs play a significant role in pattern making. They’re produced in small batch sizes for various applications. Different types of technical springs include compression springs, tension springs, torsion springs, and wave springs. These springs are specifically developed for prototype and pattern making to test the functionality and durability of the product, ensuring it meets required standards." },
    { kind: "heading", level: 2, text: "Classic Pattern Making with Strip Bent Parts" },
    { kind: "paragraph", text: "Another option in pattern making is the classic pattern making with strip bent parts. This process involves manufacturing strip bent parts in small series using original materials. It enables companies to test the final design and functionality of their products before moving into mass production. Classic pattern making offers companies the opportunity to identify potential issues and make necessary changes to enhance the quality and performance of the end product." },
    { kind: "heading", level: 2, text: "The Benefits of Prototype and Pattern Making" },
    { kind: "paragraph", text: "Prototype and pattern making offers several advantages to companies. Developing a prototype allows companies to detect potential issues early on and make necessary alterations. This reduces the risk of errors, saving time and costs in later production phases. Moreover, pattern making enables companies to test the functionality and quality of their product, ensuring it meets requirements and standards." },
    { kind: "heading", level: 2, text: "The Role of Technical Consultation" },
    { kind: "paragraph", text: "Technical consultation is crucial in prototype and pattern making. An experienced development partner can assist companies in selecting the right materials, manufacturing processes, and component design. By collaborating with a development partner, companies can ensure their prototypes and patterns meet required standards and fulfill desired functions." },
    { kind: "heading", level: 2, text: "Laser-Generated Pattern Parts and Classic Pattern Making" },
    { kind: "paragraph", text: "In our in-house development center, we produce laser-generated pattern parts and technical springs, offering small series in original parts and also classic pattern making." },
    { kind: "paragraph", text: "Laser-Generated Components" },
    { kind: "paragraph", text: "During laser generating, components are built layer by layer from powdered metallic series materials such as Steel 1.2709 or Steel 1.4543. Using state-of-the-art technologies, we reliably translate your computer-generated 3D/CAD models into their physical form. Thin layers of powder material are applied onto a base and then fused into the desired contour using a laser. This process is repeated revolvingly until the workpiece is completed in its final geometry and with the corresponding functional properties. By the way, we reclaim excess powder material in this process and fully utilize it for further productions." },
    { kind: "paragraph", text: "Technical Springs" },
    { kind: "paragraph", text: "As part of our pattern making services, we also produce technical springs in small batch sizes for your pattern application. Our portfolio includes compression springs, tension springs, torsion springs, and wave springs." },
    { kind: "paragraph", text: "Classic Pattern Making" },
    { kind: "paragraph", text: "New in our portfolio are classic pattern making services. We manufacture your strip bent parts in small series using original materials." },
    { kind: "paragraph", text: "Please discuss your desired scope in the initial consultation with us. In all areas of pattern and prototype making, our service also includes technical consultation. Leveraging our experience as your development partner, we provide insights into material selection, suitable manufacturing processes, and component design for your project. We produce all technical springs upon request in smaller batch sizes. Special packaging is offered for all products. With our in-house toolmaking and as your development partner, we also provide individual calculations for you." }
  ],
};
