// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/produkte/hybride-baugruppen/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const produkteHybrideBaugruppenDE: PageEntry = {
  id: "product.produkte-hybride-baugruppen",
  locale: "de",
  slug: "produkte/hybride-baugruppen",
  seo: {
    navLabel: "Hybride Baugruppen",
    title: "Hybride Baugruppen: Qualität & Leistung | Dietz GmbH",
    description: "Hybride Baugruppen: Qualität & Leistung",
  },
  type: "post",
  h1: "Hybride Baugruppen: Qualität & Leistung",
  cta: { kind: "typeform", typeformId: "01HHYPGYGQFR0BRFHV2WWR2ZEF", label: "Jetzt unverbindlich Kontakt mit uns aufnehmen" },
  blocks: [
    { kind: "heading", level: 2, text: "Hybride Baugruppen: Die perfekte Kombination aus Materialien und Fertigungsverfahren für innovative Baugruppen" },
    { kind: "paragraph", text: "Hybride Baugruppen sind eine spannende Entwicklung im Bereich der Baugruppenfertigung. Sie bieten die Möglichkeit, verschiedene Materialien und Fertigungsverfahren zu kombinieren, um innovative und maßgeschneiderte Lösungen zu schaffen. In diesem Artikel erfahren Sie mehr über die Vorteile und Anwendungsbereiche von hybride Baugruppen sowie die verschiedenen Herstellungsverfahren, die dabei zum Einsatz kommen." },
    { kind: "heading", level: 3, text: "Was sind hybride Baugruppen?" },
    { kind: "paragraph", text: "Hybride Baugruppen sind Baugruppen, die aus der Kombination von zwei oder mehreren Materialien und Fertigungsverfahren bestehen. Dies ermöglicht es, die Vorteile verschiedener Materialien zu nutzen und die Eigenschaften der Baugruppe optimal anzupassen. Beispiele für Materialkombinationen sind Metall und Kunststoff oder Metall und Metall." },
    { kind: "heading", level: 3, text: "Vorteile von hybriden Baugruppen" },
    { kind: "paragraph", text: "Die Verwendung von hybride Baugruppen bietet eine Vielzahl von Vorteilen. Durch die Auswahl der richtigen Materialkombination können Baugruppen mit optimalen Materialeigenschaften hergestellt werden. Zum Beispiel können die haptischen Vorteile von Silikon genutzt werden, während Kunststoff den Gewichtsvorteil bietet. Darüber hinaus ermöglichen hybride Baugruppen komplexe Formgebungen und eröffnen neue Gestaltungsmöglichkeiten." },
    { kind: "paragraph", text: "Ein weiterer Vorteil von hybriden Baugruppen ist die Flexibilität bei der Herstellung. Durch die Kombination verschiedener Fertigungsverfahren wie Stanzen, Umformen, Schweißen und Montieren können Baugruppen mit unterschiedlichen Anforderungen produziert werden. Dies ermöglicht eine maßgeschneiderte Fertigung, die den individuellen Bedürfnissen der Kunden gerecht wird." },
    { kind: "heading", level: 3, text: "Anwendungsbereiche von hybriden Baugruppen" },
    { kind: "paragraph", text: "Hybride Baugruppen finden in einer Vielzahl von Anwendungsbereichen Verwendung. Ein Beispiel sind Rasthülsenbaugruppen, bei denen Federn und Hülsen miteinander verbunden werden. Diese Baugruppen werden zum Beispiel im Interieur von Fahrzeugen eingesetzt. Durch die Kombination von Metall und Kunststoff können Bauteile geschaffen werden, die sowohl haptisch ansprechend als auch funktional sind." },
    { kind: "paragraph", text: "Ein weiteres Anwendungsbeispiel sind Draht- und Metallstanzteile mit Umspritzung. Hier werden Draht- oder Metallstanzteile mit verschiedenen Kunststoffen oder Silikonen umspritzt. Dies ermöglicht die Schaffung von Baugruppen mit optimalen Eigenschaften, wie z.B. Temperaturdurabilität und Akustik." },
    { kind: "heading", level: 3, text: "Herstellungsverfahren von hybriden Baugruppen" },
    { kind: "paragraph", text: "Die Herstellung von hybriden Baugruppen erfordert spezielle Herstellungsverfahren und Maschinen. Zu den gängigen Verfahren gehören das Stanzen, Umformen, Einbetten, Schweißen, Schrauben, Nieten und Montieren. Diese Verfahren ermöglichen die Kombination von verschiedenen Materialien und die Herstellung von komplexen Formgebungen." },
    { kind: "paragraph", text: "Die Fertigung von hybriden Baugruppen erfolgt entweder auf Sondermaschinen oder werkzeuggebunden. Je nach Material und Anforderungen können Baugruppen in verschiedenen Bandstärken und Bandbreiten hergestellt werden. Bei kleineren Losgrößen erfolgt die Montage per Hand, während bei größeren Stückzahlen eine automatisierte Fertigung angestrebt wird." },
    { kind: "heading", level: 3, text: "Montage von hybriden Baugruppen" },
    { kind: "paragraph", text: "Neben der Produktion von Federn haben wir uns auf die Herstellung von hybriden Baugruppen spezialisiert. Unser Portfolio umfasst die Kombination von zwei oder mehreren Fertigungsstufen oder Werkstoffen, z. B. Metall und Kunststoff oder Metall und Metall." },
    { kind: "heading", level: 3, text: "Fertigung auf Sondermaschinen oder werkzeuggebunden" },
    { kind: "paragraph", text: "Wir fertigen die von Ihnen gewünschten Teile werkzeuggebunden oder auf Sondermaschinen. Komplexe Formgebungen und Montageteile stellen wir in Bandstärken von 0,10 bis 3,00 mm und bis 100 mm Bandbreite her – jeweils in Abhängigkeit vom Material." },
    { kind: "paragraph", text: "Zu den von uns angebotenen Herstellungsverfahren gehören: Stanzen, Umformen, Einbetten, Schweißen, Schrauben, Nieten und Montieren. Die Montage von kleinen Losgrößen übernehmen wir per Hand, bei größeren Stückzahlen erfolgt sie automatisiert nach Ihrem Wunsch." },
    { kind: "paragraph", text: "Alle technischen Federn fertigen wir auf Anfrage auch in kleineren Losgrößen. Für alle Produkte werden auch Sonderverpackungen angeboten. Wir verfügen über einen eigenen Werkzeugbau und als Ihr Entwicklungspartner leisten wir auch individuelle Entwicklungsarbeit für Sie." },
    { kind: "heading", level: 2, text: "Kunststoff- und Silikonumspritzung" },
    { kind: "heading", level: 3, text: "Draht- und Metallstanzteile mit Umspritzung" },
    { kind: "paragraph", text: "Zum Fertigungsbereich der hybriden Baugruppen gehört auch die Umspritzung von Draht oder Metallstanzteilen mit verschiedenen Kunststoffen oder Silikonen." },
    { kind: "heading", level: 3, text: "Fertigung mit optimalen Materialeigenschaften" },
    { kind: "paragraph", text: "Um das gewünschte Bremselement mit optimalen Eigenschaften auszustatten, nutzen wir bei diesen Materialkombinationen zum einen die Temperaturdurabilität und die haptischen Vorteile von Silikon und zum anderen den Gewichtsvorteil von Kunststoff. In der Regel sind damit äußerst komplexe Fertigungsprozesse verbunden, die im Verbund stattfinden und bei denen wir eine Automatisierung anstreben." },
    { kind: "paragraph", text: "Alle technischen Federn fertigen wir auf Anfrage auch in kleineren Losgrößen. Für alle Produkte werden auch Sonderverpackungen angeboten. Wir verfügen über einen eigenen Werkzeugbau und als Ihr Entwicklungspartner leisten wir für Sie auch individuelle Berechnungen." },
    { kind: "heading", level: 2, text: "Rasthülsenbaugruppen" },
    { kind: "heading", level: 3, text: "Hülsenbaugruppen mit Metall und Kunststoff" },
    { kind: "paragraph", text: "Hülsenbaugruppen, also die Verbindung von Federn und Hülsen, gehören zum Portfolio der hybriden Bauteile. Sie kommen in vielfältigen Anwendungsbereichen zum Einsatz – etwa im Interieur verschiedenster Automobile." },
    { kind: "heading", level: 3, text: "Maßgeschneiderte Fertigung in vielfältigen Verfahren" },
    { kind: "paragraph", text: "Bei der Herstellung Ihrer Rasthülsenbaugruppen kombinieren wir Metall und Kunststoff in vielfältigen Verfahren, die sich je nach Aufgabenstellung und Material individuell festlegen lassen. Die Kombination von Kunststoff und Metall vereint die vorteilhaften Eigenschaften bezüglich Haptik, Akustik und Funktionalität in einem maßgeschneiderten Bauteil. Alle technischen Federn fertigen wir auf Anfrage auch in kleineren Losgrößen. Für alle Produkte werden auch Sonderverpackungen angeboten. Wir verfügen über einen eigenen Werkzeugbau und als Ihr Entwicklungspartner leisten wir auch individuelle Berechnungen für Sie." }
  ],
};
