// Generated by scripts/migrate/gen-from-live.py from https://www.dietz.eu/produkte/wellenfedern/
// Source of truth is the LIVE page, not the original markdown scrape
// (which was incomplete: this content type was missed entirely, and
// several pages were captured as summaries rather than verbatim copy).
import type { PageEntry } from "@/content/schema";

export const produkteWellenfedernDE: PageEntry = {
  id: "product.produkte-wellenfedern",
  locale: "de",
  slug: "produkte/wellenfedern",
  seo: {
    navLabel: "Wellenfedern",
    title: "Wellenfedern nach Maß vom Hersteller | Dietz GmbH",
    description:
      "Wellenfedern aus Flachdraht nach Maß: platzsparend und präzise, für Polstermöbel, Automotive und Maschinenbau. Jetzt Anfrage stellen.",
  },
  type: "post",
  h1: "Wellenfedern: Robustheit & Zuverlässigkeit",
  cta: { kind: "typeform", typeformId: "01HHYPGYGQFR0BRFHV2WWR2ZEF", label: "Jetzt unverbindlich Kontakt mit uns aufnehmen" },
  blocks: [
    { kind: "image", src: "/images/live/dtz-wellenring-vorspann.jpg", alt: "Wellenfedern: Robustheit & Zuverlässigkeit", width: 1400, height: 1120 },
    { kind: "heading", level: 2, text: "Alles, was Sie über Wellenfedern wissen müssen" },
    { kind: "paragraph", text: "Wellenfedern sind eine innovative Lösung für die unterschiedlichsten Anwendungen, bei denen Platz und Effizienz entscheidend sind. In diesem Artikel werden wir alles beleuchten, was Sie über Wellenfedern wissen müssen. Von ihrer Definition und Funktionsweise bis hin zu ihren Vorteilen und Anwendungsbeispielen – erfahren Sie, warum Wellenfedern eine hervorragende Wahl für Ihre Konstruktionen sein können." },
    { kind: "heading", level: 3, text: "Was sind Wellenfedern?" },
    { kind: "paragraph", text: "Wellenfedern sind federnde Bauteile, die aus Flachmaterial gefertigt werden. Im Gegensatz zu herkömmlichen Drahtfedern zeichnen sich Wellenfedern durch ihre geringe Höhe und ihre hohe Federkraft aus. Das innovative Design der Wellenfedern ermöglicht es, Platz zu sparen und gleichzeitig eine zuverlässige Federung zu gewährleisten." },
    { kind: "heading", level: 3, text: "Funktionsweise von Wellenfedern" },
    { kind: "paragraph", text: "Die Funktionsweise von Wellenfedern basiert auf der gewundenen Struktur des Flachmaterials. Durch diese Struktur werden die Kräfte gleichmäßig über die gesamte Feder verteilt, wodurch eine hohe Tragfähigkeit erreicht wird. Die Wellenfedern können sowohl axiale als auch radiale Kräfte aufnehmen und bieten eine präzise und vorhersagbare Federung." },
    { kind: "heading", level: 3, text: "Vorteile von Wellenfedern" },
    { kind: "paragraph", text: "Wellenfedern bieten eine Vielzahl von Vorteilen, die sie zu einer attraktiven Wahl für Konstrukteure machen. Hier sind einige der wichtigsten Vorteile von Wellenfedern:" },
    { kind: "heading", level: 3, text: "Platzersparnis" },
    { kind: "paragraph", text: "Dank ihres innovativen Designs ermöglichen Wellenfedern eine erhebliche Reduzierung der Federhöhe im Vergleich zu herkömmlichen Drahtfedern. Dies ist besonders vorteilhaft in Anwendungen mit begrenztem Bauraum, bei denen Platz ein kostbares Gut ist." },
    { kind: "heading", level: 3, text: "Hohe Federkraft" },
    { kind: "paragraph", text: "Trotz ihrer geringen Höhe bieten Wellenfedern eine hohe Federkraft. Dies ermöglicht eine effektive Federung und sorgt dafür, dass die gewünschte Belastung präzise und vorhersagbar ist." },
    { kind: "heading", level: 3, text: "Vielseitige Anwendungsmöglichkeiten" },
    { kind: "paragraph", text: "Wellenfedern finden in verschiedenen Branchen und Anwendungsbereichen Anwendung. Von der Luft- und Raumfahrt über die Automobilindustrie bis hin zur Medizintechnik – die Einsatzmöglichkeiten sind vielfältig." },
    { kind: "heading", level: 3, text: "Leichtgewichtige Bauweise" },
    { kind: "paragraph", text: "Dank ihres Flachmaterialdesigns sind Wellenfedern leichter als herkömmliche Drahtfedern. Dies spart nicht nur Materialkosten, sondern erleichtert auch die Montage und Handhabung der Bauteile." },
    { kind: "heading", level: 3, text: "Anwendungsbeispiele für Wellenfedern" },
    { kind: "paragraph", text: "Wellenfedern finden in zahlreichen Anwendungen Verwendung. Hier sind einige Beispiele, wie Wellenfedern in der Praxis eingesetzt werden können:" },
    { kind: "heading", level: 3, text: "Wasserventil" },
    { kind: "paragraph", text: "Ein Anwendungsbeispiel für Wellenfedern ist ein Wasserventil. Durch den Einsatz einer Wellenfeder wird eine unerwünschte Drehung des Ventilgriffs verhindert. Die Wellenfeder sorgt dafür, dass die Ventilposition beibehalten wird, indem sie eine konstante Last aufrechterhält und in die Gewinde der Hauptwelle eingreift." },
    { kind: "heading", level: 3, text: "Elektronik" },
    { kind: "paragraph", text: "In der Elektronikindustrie werden Wellenfedern häufig zur Kontaktsicherung in Steckverbindungen eingesetzt. Dank ihrer kompakten Bauweise und hohen Federkraft bieten sie eine zuverlässige Verbindung und gewährleisten eine stabile elektrische Verbindung." },
    { kind: "heading", level: 3, text: "Automobilindustrie" },
    { kind: "paragraph", text: "In der Automobilindustrie werden Wellenfedern in verschiedenen Anwendungen eingesetzt, wie zum Beispiel in Kupplungen, Stoßdämpfern und Bremsen. Sie bieten eine präzise und zuverlässige Federung, die in einem Fahrzeug von entscheidender Bedeutung ist." },
    { kind: "heading", level: 3, text: "Sonderanfertigung von Wellenfedern" },
    { kind: "paragraph", text: "Wenn Sie spezielle Anforderungen haben, bieten viele Hersteller die Möglichkeit, Wellenfedern nach Ihren individuellen Vorgaben anzufertigen. Von der Auswahl des Materials bis hin zur Oberflächenbehandlung – Sie können sicher sein, dass die Wellenfedern genau auf Ihre Bedürfnisse zugeschnitten sind." },
    { kind: "heading", level: 2, text: "Maßgeschneiderte Entwicklung der Wellenfedern" },
    { kind: "paragraph", text: "Wellenfedern sind eine innovative Lösung für Konstruktionen, bei denen Platz und Effizienz entscheidend sind. Dank ihres einzigartigen Designs bieten sie Platzersparnis, hohe Federkraft und vielseitige Anwendungsmöglichkeiten. Wenn Sie nach einer effektiven und zuverlässigen Federungslösung suchen, sollten Sie die Verwendung von Wellenfedern in Betracht ziehen." },
    { kind: "paragraph", text: "Wir entwickeln die Wellenfedern in engster Abstimmung mit Ihnen speziell für den benötigten Einsatzbereich. Bei Bedarf unterstützen wir Sie gern von der Dimensionierung über die Nachrechnung bis zur Fertigung. Mit unserer speziellen Fachkompetenz finden wir gemeinsam die für Sie passende Lösung." },
    { kind: "paragraph", text: "Wir fertigen sowohl Single-Turn als auch Multi-Turn-Ausführungen mit welliger und gerader Oberfläche." },
    { kind: "paragraph", text: "Alle technischen Federn fertigen wir auf Anfrage auch in kleineren Losgrößen. Für alle Produkte werden auch Sonderverpackungen angeboten. Wir verfügen über einen eigenen Werkzeugbau und als Ihr Entwicklungspartner leisten wir auch individuelle Entwicklungsarbeit für Sie." }
  ],
  gallery: [
    { heading: "Wellenring", caption: "Wellenring als Vorspannelement und Toleranzausgleich in einer Baugruppe.", href: "/produkte/wellenring/", image: { src: "/images/live/dtz-wellenring-vorspann.jpg", alt: "Wellenring Vorspannelement" } },
    { heading: "Wellenfederturm für Thermomanagementsystem", caption: "Fertigung mit Sonderwerkzeugen und Kameraüberwachung für höchste Genauigkeit", href: "/produkte/wellenfederturm-fuer-thermomanagementsystem/", image: { src: "/images/live/wellenfederturm.jpg", alt: "Wellenfederturm" } },
  ],
};
