/**
 * Compare the live site's URLs against the rebuild's routes.
 *
 * This is the highest-risk item in any replatform. A live URL that has no route
 * in the new site does not degrade — it 404s, and every link and every ranking
 * pointing at it is lost on the day of the switch. The only defence is to know
 * exactly which URLs those are before launch and to redirect each one.
 *
 * Emits three buckets:
 *   matched     — live URL exists in the rebuild. Nothing to do.
 *   live-only   — live URL has no route. **Needs a 301, or it is a lost page.**
 *   built-only  — new page with no live counterpart. Expected for pages we
 *                 added deliberately; anything else is worth a second look.
 *
 * Also writes a paste-ready nginx map. Note that Next's `redirects()` config
 * does nothing under `output: "export"` — a static export has no server to run
 * it — so the redirects must live in the web server.
 *
 *   node scripts/seo/url-parity.mjs
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

const LIVE = "reference/_source-lists/all_de_en_urls.txt";
const OUT_JSON = "reference/seo/url-parity.json";
const OUT_NGINX = "reference/seo/redirects.nginx.conf";

// Pages we added that never existed on the live site. Listing them here is what
// separates "deliberately new" from "accidentally orphaned".
const INTENTIONALLY_NEW = new Set([
  "/wissen/",
  "/en/resources/",
  "/en/careers/",
]);

function livePaths() {
  const out = new Set();
  for (const line of readFileSync(LIVE, "utf8").split("\n")) {
    const url = line.trim();
    if (!url) continue;
    try {
      const u = new URL(url);
      let p = u.pathname;
      if (!p.endsWith("/")) p += "/";
      out.add(p);
    } catch {
      /* not a URL; skip */
    }
  }
  return out;
}

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (p.endsWith(".ts") && !p.endsWith("index.ts")) out.push(p);
  }
  return out;
}

function builtFromContent() {
  const out = new Set();
  for (const f of walk("src/content/pages")) {
    const s = readFileSync(f, "utf8");
    const loc = s.match(/\n  locale: "(\w+)"/);
    const slug = s.match(/\n  slug: "([^"]*)"/);
    if (!loc || !slug) continue;
    const path =
      loc[1] === "de" ? `/${slug[1]}` : `/${loc[1]}/${slug[1]}`;
    out.add(path === "/" ? "/" : `${path.replace(/\/+$/, "")}/`);
  }
  return out;
}

const live = livePaths();
const built = builtFromContent();

const matched = [...live].filter((p) => built.has(p)).sort();
const liveOnly = [...live].filter((p) => !built.has(p)).sort();
const builtOnly = [...built]
  .filter((p) => !live.has(p) && !INTENTIONALLY_NEW.has(p))
  .sort();

/**
 * Best-guess redirect target for a lost URL: the deepest existing ancestor.
 * Deliberately conservative — a redirect to a section page keeps the link
 * equity and lands the reader somewhere true, whereas guessing at a specific
 * replacement page risks sending them somewhere wrong.
 */
function suggestTarget(path) {
  const parts = path.replace(/^\/|\/$/g, "").split("/");
  while (parts.length > 1) {
    parts.pop();
    const candidate = `/${parts.join("/")}/`;
    if (built.has(candidate)) return candidate;
  }
  return path.startsWith("/en/") ? "/en/" : "/";
}

const suggestions = liveOnly.map((p) => ({ from: p, to: suggestTarget(p) }));

mkdirSync("reference/seo", { recursive: true });
writeFileSync(
  OUT_JSON,
  JSON.stringify(
    {
      _comment: [
        "Generated by scripts/seo/url-parity.mjs — do not hand-edit.",
        "liveOnly is the launch-blocking list: each of these URLs exists today,",
        "has whatever links and rankings it has accumulated, and returns 404 in",
        "the rebuild unless redirected.",
        "`to` is a conservative suggestion (nearest surviving ancestor), not a",
        "decision. Review before shipping.",
      ],
      counts: {
        live: live.size,
        built: built.size,
        matched: matched.length,
        liveOnly: liveOnly.length,
        builtOnly: builtOnly.length,
      },
      liveOnly: suggestions,
      builtOnly,
      matched,
    },
    null,
    2,
  ) + "\n",
);

const nginx = [
  "# 301 redirects for URLs that exist on the live site but not in the rebuild.",
  "# Generated by scripts/seo/url-parity.mjs. REVIEW BEFORE SHIPPING — the",
  "# targets are nearest-surviving-ancestor guesses, not editorial decisions.",
  "#",
  "# Next.js `redirects()` is a no-op under `output: \"export\"`, so these have",
  "# to live in the web server. Include inside the server block:",
  "#     include /etc/nginx/dietz-redirects.conf;",
  "",
  ...suggestions.map((s) => `location = ${s.from} { return 301 ${s.to}; }`),
  "",
].join("\n");
writeFileSync(OUT_NGINX, nginx);

console.log(`live URLs      ${live.size}`);
console.log(`built routes   ${built.size}`);
console.log(`matched        ${matched.length}`);
console.log(`live-only      ${liveOnly.length}   <- need 301s`);
console.log(`built-only     ${builtOnly.length}`);
console.log(`\nwrote ${OUT_JSON}`);
console.log(`wrote ${OUT_NGINX}`);
if (liveOnly.length) {
  console.log("\nfirst 15 live-only URLs:");
  for (const s of suggestions.slice(0, 15)) console.log(`  ${s.from}  ->  ${s.to}`);
}
