import { allEntries } from "@/content/pages";
import { localeHref } from "@/lib/locale";
import type { PageEntry } from "@/content/schema";

// Reverse index: which listing page enumerates a given page.
//
// Roughly 250 glossary, blog and news pages sit on flat root slugs
// (`/federkraft/`), so their URL has no parent segment for a breadcrumb to
// walk and the trail bottoms out at Home. Their real parent is whichever
// index links to them — which the listings now state outright, so this is
// read from the content rather than hand-maintained anywhere.
//
// Lives outside `pages/index.ts` because that file is regenerated by
// scripts/content/generate-registry.mjs and would lose anything added to it.
const byHref = new Map<string, PageEntry>();

for (const entry of allEntries()) {
  if (entry.type !== "listing") continue;
  for (const item of entry.items) {
    if (item.href && !byHref.has(item.href)) byHref.set(item.href, entry);
  }
}

/** The listing that links to this page, if any. Never the page itself. */
export function listingParent(entry: PageEntry): PageEntry | undefined {
  const parent = byHref.get(localeHref(entry.locale, entry.slug));
  return parent === entry ? undefined : parent;
}
